---
title: "data_analysis_qp"
output: html_document
date: "2024-01-20"
editor_options: 
  chunk_output_type: console
---

```{r}
library(tidyverse)
library(lme4)
library(ggplot2)
library(papaja)
library(tinylabels)
library(car)
library(broom)
library(emmeans)
library(reshape2)
library(writexl)
library(readxl)
library(dplyr)
library(here)
```

```{r}

qp_data_raw_1 <- read_excel("~/Library/Mobile Documents/com~apple~CloudDocs/RUTGERS/PhD/SECOND YEAR/QP/RESULTS/qp_data_analysis/data/qp_data_raw_1.xlsx")

View(qp_data_raw_1)


qp_data <- qp_data_raw_1[-(100:126),]

knitr::kable(head(qp_data$political_orientation))

qp_data$age <- as.numeric(qp_data$age)

summary(qp_data$age)


qp_data$political_orientation <- factor(qp_data$political_orientation, levels = c("Far left", "Left", "Center-Left", "Centre", "Center-Right", "Right"))

qp_data$mother_tongue <- factor(qp_data$mother_tongue, levels = c("Catalan", "Both", "Spanish", "Other(s)"))



qp_data$political_orientation <- factor(qp_data$political_orientation, levels = c("Center-Left", "Center-Right", "Centre", "Far left", "Left", "Right"))


#summary(qp_data_norm <- qp_data %>%
         # group_by(id) %>%
          #mutate(score_norm = (score-mean(score))/sd(score)))

#write.table(qp_data_norm, "qp_data_norm.txt")

```

```{r}

mean(qp_data$age)

gender_summary <- qp_data %>%
  group_by(gender) %>%
  summarise(
    total_count = n(),
    avg_age = mean(age, na.rm = TRUE),
    sd_age = sd(age, na.rm = TRUE)
  ) %>%
  bind_rows(qp_data %>%
              summarise(
                gender = "Total",
                total_count = n(),
                avg_age = mean(age, na.rm = TRUE),
                sd_age = sd(age, na.rm = TRUE)
              )) %>%
  rename(
   'Gender' = gender,
    'Total Count' = total_count,
    'Average Age' = avg_age,
    'SD' = sd_age
  )


pivot_wider(names_from = gender, values_from = c(total_count, avg_age, sd_age))

print(gender_summary)

knitr::kable(gender_summary)

```


```{r}
summary(qp_data)


qp_data$age_arrive_in_Spain<-as.numeric(qp_data$age_arrive_in_Spain)



```


```{r}
summary(qp_data$political_orientation)

summary(qp_data$age)

qp_data$political_orientation


```

```{r}


qp_data_identity_separated <- qp_data %>%
  mutate(Palmesan = ifelse(grepl("Palmesan", identity), "Yes", "No"),
         Mallorcan = ifelse(grepl("Mallorcan", identity), "Yes", "No"),
         Balearic = ifelse(grepl("Balearic", identity), "Yes", "No"),
         Catalan = ifelse(grepl("Catalan", identity), "Yes", "No"),
         Catalan_countries = ifelse(grepl("Catalan countries", identity), "Yes", "No"),
         Spanish = ifelse(grepl("Spanish", identity), "Yes", "No"),
         European = ifelse(grepl("European", identity), "Yes", "No"))
         

view(qp_data_identity_separated)
```


```{r, plots}
plot(table(qp_data$political_orientation))

table(qp_data$political_orientation)

table(filter(qp_data, political_orientation == "Center-Right"))
  

select(qp_data, Since_we_all_speak_Spanish_it_is_not_necessary_that_people_who_come_from_other_Autonomous_Communities_or_Spanish_speaking_countries_learn_Catalan) %>%
  if_any(qp_data, political_orientation == "Center-right")


# Filter the data for those who identified as center-right
center_right_data <- subset(qp_data, political_orientation == "Center-Right")

center_data <- subset(qp_data, political_orientation == "Centre")


progressive_data <- subset(qp_data, political_orientation == "Far left")

progressive_data_1 <- subset(qp_data, political_orientation == "Left")


qp_data |>

  
  
library(dplyr)

# Assuming 'qp_data' is your dataframe
# You can use the filter function from dplyr to create subsets based on conditions
far_left_catalan <- qp_data %>% filter(political_orientation == "Far left" & mother_tongue == "Catalan")
left_catalan <- qp_data %>% filter(political_orientation == "Left" & mother_tongue == "Catalan")
center_left_catalan <- qp_data %>% filter(political_orientation == "Center-Left" & mother_tongue == "Catalan")

# Count the number of rows in each subset
count_far_left_catalan <- nrow(far_left_catalan)
count_left_catalan <- nrow(left_catalan)
count_center_left_catalan <- nrow(center_left_catalan)

# Create a table with the counts
table_political_orientation_mother_tongue <- data.frame(
  Political_Orientation = c("Far left", "Left", "Center-Left"),
  Mother_Tongue = c("Catalan", "Catalan", "Catalan"),
  Count = c(count_far_left_catalan, count_left_catalan, count_center_left_catalan)
)

print(table_political_orientation_mother_tongue)

  

# Assuming 'qp_data' is your dataframe
# You can use the filter function from dplyr to create subsets based on conditions
far_left_catalan <- qp_data %>% filter(political_orientation == "Far left")
left_catalan <- qp_data %>% filter(political_orientation == "Left")
center_left_catalan <- qp_data %>% filter(political_orientation == "Center-Left")

# Count the number of rows in each subset
count_far_left_catalan <- nrow(far_left_catalan)
count_left_catalan <- nrow(left_catalan)
count_center_left_catalan <- nrow(center_left_catalan)

# Create a table with the counts
table_political_orientation_mother_tongue <- data.frame(
  Political_Orientation = c("Far left", "Left", "Center-Left"),
  Count = c(count_far_left_catalan, count_left_catalan, count_center_left_catalan)
)

print(table_political_orientation_mother_tongue)





# Calculate the mean of responses for those who identified as center-right
mean_center_right <- mean(center_right_data$Since_we_all_speak_Spanish_it_is_not_necessary_that_people_who_come_from_other_Autonomous_Communities_or_Spanish_speaking_countries_learn_Catalan)

# Print the mean
print(mean_center_right)




# Filter the data for those who identified as center-right
center_right_data <- subset(qp_data, political_orientation == "Center-Right")

# Calculate the mean of responses for those who identified as center-right
mean_center_right <- mean(center_right_data$Catalan_is_an_identity_element_of_the_Balearic_Islands)

# Print the mean
print(mean_center_right)



# Filter the data for those who identified as center-right
center_right_data <- subset(qp_data, political_orientation == "Center-Right")

# Calculate the mean of responses for those who identified as center-right
mean_center_right <- mean(center_right_data$People_should_put_more_effort_into_using_Spanish)

# Print the mean
print(mean_center_right)


mean(qp_data$It_should_be_mandatory_for_all_students_from_the_Balearic_Islands_to_take_at_least_50_of_their_subjects_in_Spanish)



# Sample data
qp_data <- data.frame(political_orientation = c("Liberal", "Conservative", "Moderate", "Liberal", "Conservative"))

# Define colors for each political orientation
colors <- c("blue", "red", "green", "purple", "yellow", "orange")

# Create a color bar plot
barplot(table(qp_data$political_orientation), col = colors, main = "Political Orientation Bar Plot", xlab = "Political Orientation", ylab = "Frequency", las = 1)


qp_data$political_orientation <- factor(qp_data$political_orientation, levels = c("Center-Left", "Center-Right", "Centre", "Far left", "Left", "Right"))


qp_data$political_orientation <- factor(qp_data$political_orientation, levels = c("Far left", "Left", "Center-Left", "Centre", "Center-Right", "Right"))


# Horizontal bar plot with rotated axis labels

barplot(table(qp_data$political_orientation), col = colors, main = "Political Orientation Bar Plot", xlab = "Frequency", ylab = "Political Orientation", las = 1)


ggplot(
  data = qp_data, 
  aes(
    x = political_orientation, fill = political_orientation)) + 
  geom_bar() +
    scale_fill_manual(values = c("indianred2", "indianred2", "indianred2", "cornflowerblue", "cornflowerblue", "cornflowerblue"))


ggplot(
  data = qp_data, 
  aes(
    x = political_orientation, 
    fill = political_orientation)) + 
  geom_bar() +
  scale_x_discrete(labels = c("Far left" = "Far-Left")) +
  scale_fill_manual(values = c("indianred2", "indianred2", "indianred2", "cornflowerblue", "cornflowerblue", "cornflowerblue")) +
  labs(y = "Count", fill = "Political orientation", x = "Political orientation")


ggplot(
  data = qp_data, 
  aes(
    x = political_orientation, 
    fill = political_orientation)) + 
  geom_bar() +
  scale_x_discrete(labels = c("Far left" = "Far-Left")) +
  scale_fill_manual(
    values = c("indianred2", "indianred2", "indianred2", "cornflowerblue", "cornflowerblue", "cornflowerblue"),
    name = "Political orientation") +  # Set the legend title
  labs(y = "Count", x = "Political orientation")





plot(plot1<-qp_data %>%
       ggplot() +
       aes(x=gender, fill=political_orientation) +
       geom_bar(stat="count", position="dodge"))


plot(plot <- qp_data %>%
       ggplot() +
       aes(x=gender, y=age, col=age) +
       geom_point(na.rm = TRUE))


plot(plot1<-qp_data %>%
       ggplot() +
       aes(x=political_orientation, fill=gender) +
       geom_bar(stat="count", position="dodge"))

plot(plot1<-qp_data %>%
       ggplot() +
       aes(x=political_orientation, fill=gender) +
       geom_bar(stat="count", position="stack"))


qp_data %>%
  ggplot(aes(x = gender, y = age, color = political_orientation)) +
  geom_boxplot()

qp_data %>%
  group_by(gender, family_income) %>%
  summarise(count = n()) %>%
  ggplot(aes(x = gender, y = count, fill = family_income)) +
  geom_bar(stat = "identity", position = "stack") +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))


qp_data %>%
  filter(family_income != "I prefer not to say") %>%
  group_by(gender, family_income) %>%
  summarise(count = n()) %>%
  ggplot(aes(x = gender, y = count, fill = family_income)) +
  geom_bar(stat = "identity", position = "stack") +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))

qp_data %>%
  filter(family_income != "I prefer not to say") %>%
  group_by(gender, family_income) %>%
  summarise(count = n()) %>%
  ggplot(aes(x = gender, y = count, fill = family_income)) +
  geom_bar(stat = "identity", position = "fill") +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))




```


```{r, political orientation not complete}

mod_null_lang_identity <- lm(Catalan_is_an_identity_element_of_the_Balearic_Islands ~ 1, data = qp_data)

mod_1_lang_identity <- lm(Catalan_is_an_identity_element_of_the_Balearic_Islands ~ 1 + political_orientation, data = qp_data)

mod_2_lang_identity <- lm(Catalan_is_an_identity_element_of_the_Balearic_Islands ~ 1 + political_orientation + gender, data = qp_data)

mod_int_lang_identity <- lm(Catalan_is_an_identity_element_of_the_Balearic_Islands ~ 1 + political_orientation + gender + political_orientation:gender, data = qp_data)

summary(mod_int_lang_identity)

anova(mod_null_lang_identity, mod_1_lang_identity, mod_2_lang_identity, mod_int_lang_identity)

plot(mod_int_lang_identity)


ggplot(
  data = qp_data, 
  aes(
    x = political_orientation,
    y = Catalan_is_an_identity_element_of_the_Balearic_Islands)) + 
  geom_point() + 
  geom_boxplot()


```

```{r, political orientation and catalan as an identity element}

mod_null_lang_identity <- lm(Catalan_is_an_identity_element_of_the_Balearic_Islands ~ 1, data = qp_data)

mod_1_lang_identity <- lm(Catalan_is_an_identity_element_of_the_Balearic_Islands ~ 1 + political_orientation, data = qp_data)

mod_2_lang_identity <- lm(Catalan_is_an_identity_element_of_the_Balearic_Islands ~ 1 + political_orientation + gender, data = qp_data)

mod_3_lang_identity <- lm(Catalan_is_an_identity_element_of_the_Balearic_Islands ~ 1 + political_orientation + gender + age, data = qp_data)

mod_4_lang_identity <- lm(Catalan_is_an_identity_element_of_the_Balearic_Islands ~ 1 + political_orientation + gender + age + level_of_education, data = qp_data)

mod_5_lang_identity <- lm(Catalan_is_an_identity_element_of_the_Balearic_Islands ~ 1 + political_orientation + gender + age + level_of_education + employment, data = qp_data)

mod_6_lang_identity <- lm(Catalan_is_an_identity_element_of_the_Balearic_Islands ~ 1 + political_orientation + gender + age + level_of_education + employment + family_income, data = qp_data)

mod_7_lang_identity <- lm(Catalan_is_an_identity_element_of_the_Balearic_Islands ~ 1 + political_orientation + gender + age + level_of_education + employment + family_income + mother_tongue, data = qp_data)

mod_int_lang_identity <- lm(Catalan_is_an_identity_element_of_the_Balearic_Islands ~ 1 + political_orientation + gender + age + political_orientation *gender*age:level_of_education:employment:family_income:mother_tongue, data = qp_data)

summary(mod_1_lang_identity)

summary(mod_2_lang_identity)

summary(mod_3_lang_identity)

summary(mod_4_lang_identity)

summary(mod_5_lang_identity)

summary(mod_6_lang_identity)

summary(mod_7_lang_identity)


anova(mod_null_lang_identity,mod_1_lang_identity, mod_2_lang_identity, mod_3_lang_identity, mod_4_lang_identity, mod_5_lang_identity, mod_6_lang_identity, mod_7_lang_identity)

anova(mod_5_lang_identity, mod_6_lang_identity)

anova(mod_null_lang_identity,mod_1_lang_identity, mod_7_lang_identity)


ggplot(
  data = qp_data, 
  aes(
    x = political_orientation,
    y = Catalan_is_an_identity_element_of_the_Balearic_Islands, colors = political_orientation)) + 
  geom_point() + 
  geom_boxplot()

```


```{r}
mod_null_lang_identity_1 <- lm(Catalan_is_an_identity_element_of_the_Balearic_Islands ~ 1, data = qp_data)

mod_1_lang_identity_1 <- lm(Catalan_is_an_identity_element_of_the_Balearic_Islands ~ 1 + political_orientation, data = qp_data)

mod_2_lang_identity_1 <- lm(Catalan_is_an_identity_element_of_the_Balearic_Islands ~ 1 + political_orientation + gender, data = qp_data)

mod_3_lang_identity_1 <- lm(Catalan_is_an_identity_element_of_the_Balearic_Islands ~ 1 + political_orientation + gender + age, data = qp_data)

mod_4_lang_identity_1 <- lm(Catalan_is_an_identity_element_of_the_Balearic_Islands ~ 1 + political_orientation + gender + age + level_of_education, data = qp_data)

mod_5_lang_identity_1 <- lm(Catalan_is_an_identity_element_of_the_Balearic_Islands ~ 1 + political_orientation + gender + age + level_of_education + employment, data = qp_data)

mod_6_lang_identity_1 <- lm(Catalan_is_an_identity_element_of_the_Balearic_Islands ~ 1 + political_orientation + gender + age + level_of_education + employment + family_income, data = qp_data)

mod_7_lang_identity_1 <- lm(Catalan_is_an_identity_element_of_the_Balearic_Islands ~ 1 + political_orientation + gender + age + level_of_education + employment + family_income + mother_tongue, data = qp_data)

mod_int_lang_identity_1 <- lm(Catalan_is_an_identity_element_of_the_Balearic_Islands ~ 1, political_orientation:gender:age:level_of_education:employment:family_income:mother_tongue, data = qp_data)

plot(mod_2_lang_identity_1)


summary(mod_1_lang_identity_1)

summary(mod_int_lang_identity)

summary(mod_2_lang_identity_1)

summary(mod_3_lang_identity_1)

summary(mod_4_lang_identity_1)

summary(mod_5_lang_identity_1)

summary(mod_6_lang_identity_1)

summary(mod_7_lang_identity_1)


anova(mod_null_lang_identity_1,mod_1_lang_identity_1, mod_2_lang_identity_1, mod_3_lang_identity_1, mod_4_lang_identity_1, mod_5_lang_identity_1, mod_6_lang_identity_1, mod_7_lang_identity_1)


ggplot(
  data = qp_data, 
  aes(
    x = political_orientation,
    y = Catalan_is_an_identity_element_of_the_Balearic_Islands, fill = political_orientation)) + 
  geom_point() + 
  geom_boxplot() +
  labs(x = "Political orientation", y = "Catalan is an identity element of the Balearic Islands", fill = "Political Orientation") +
    scale_fill_manual(values = c("indianred2", "indianred2", "indianred2", "cornflowerblue", "cornflowerblue", "cornflowerblue"))

ggplot(
  data = qp_data, 
  aes(
    x = political_orientation,
    y = Catalan_is_an_identity_element_of_the_Balearic_Islands, 
    fill = political_orientation)) + 
  geom_point(size = 1) +  # Set the size of the points on the plot
  stat_summary(fun.data = mean_se, geom = "pointrange", pch = 23, size = 1) +
  labs(x = "Political orientation", y = "Catalan is an identity element of the Balearic Islands", fill = "Political Orientation") +
  scale_fill_manual(values = c("indianred2", "indianred2", "indianred2", "cornflowerblue", "cornflowerblue", "cornflowerblue")) +
  theme(
    legend.key.size = unit(1, "lines"),  # Set the size of the legend key
    legend.key.width = unit(1.5, "lines"),  # Set the width of the legend key
    legend.spacing.x = unit(0.5, "lines")  # Adjust spacing between legend items
  ) +
  guides(fill = guide_legend(override.aes = list(size = 0.5)))  # Set the size of points in the legend

```





```{r, catalan identity element as a function of neighborhood}

mod_null_lang_identity_neig <- lm(Catalan_is_an_identity_element_of_the_Balearic_Islands ~ 1, data = qp_data)

mod_1_lang_identity_neig <- lm(Catalan_is_an_identity_element_of_the_Balearic_Islands ~ 1 + neighborhood, data = qp_data)

mod_2_lang_identity_neig <- lm(Catalan_is_an_identity_element_of_the_Balearic_Islands ~ 1 + neighborhood + political_orientation, data = qp_data)

mod_3_lang_identity_neig <- lm(Catalan_is_an_identity_element_of_the_Balearic_Islands ~ 1 + neighborhood + political_orientation + age, data = qp_data)

mod_4_lang_identity_neig <- lm(Catalan_is_an_identity_element_of_the_Balearic_Islands ~ 1 + neighborhood + political_orientation + age + gender, data = qp_data)

mod_int_lang_identity_neig <- lm(Catalan_is_an_identity_element_of_the_Balearic_Islands ~ 1 + neighborhood + political_orientation + age + gender + neighborhood:political_orientation:age:gender, data = qp_data)

anova(mod_null_lang_identity_neig, mod_1_lang_identity_neig, mod_2_lang_identity_neig, mod_3_lang_identity_neig, mod_4_lang_identity_neig, mod_int_lang_identity_neig)


```

```{r, I like it when people speak Catalan as a function of political orientation}

mod_null_like_use_Catalan <- lm(I_like_that_people_use_Catalan ~ 1, data = qp_data)

mod_1_like_use_Catalan <- lm(I_like_that_people_use_Catalan ~ 1 + political_orientation, data = qp_data)

mod_2_like_use_Catalan <- lm(I_like_that_people_use_Catalan ~ 1 + political_orientation + gender, data = qp_data)

mod_3_like_use_Catalan <- lm(I_like_that_people_use_Catalan ~ 1 + political_orientation + gender + age, data = qp_data)

mod_int_like_use_Catalan <- lm(I_like_that_people_use_Catalan ~ 1 + political_orientation + gender + age + political_orientation:gender:age, data = qp_data)

summary(mod_null_like_use_Catalan)
summary(mod_1_like_use_Catalan)
summary(mod_2_like_use_Catalan)
summary(mod_3_like_use_Catalan)
summary(mod_int_like_use_Catalan)

anova(mod_null_like_use_Catalan, mod_1_like_use_Catalan, mod_2_like_use_Catalan, mod_3_like_use_Catalan, mod_int_like_use_Catalan)


ggplot(
  data = qp_data, 
  aes(
    x = political_orientation,
    y = I_like_that_people_use_Catalan, 
    fill = political_orientation)) + 
  geom_point(size = 1) +  # Set the size of the points on the plot
  stat_summary(fun.data = mean_se, geom = "pointrange", pch = 23, size = 1) +
  labs(x = "Political orientation", y = "I like that people use Catalan", fill = "Political Orientation") +
  scale_fill_manual(values = c("indianred2", "indianred2", "indianred2", "cornflowerblue", "cornflowerblue", "cornflowerblue")) +
  theme(
    legend.key.size = unit(1, "lines"),  # Set the size of the legend key
    legend.key.width = unit(1.5, "lines"),  # Set the width of the legend key
    legend.spacing.x = unit(0.5, "lines")  # Adjust spacing between legend items
  ) +
  guides(fill = guide_legend(override.aes = list(size = 0.5)))  # Set the size of points in the legend










ggplot(
  data = qp_data, 
  aes(
    x = political_orientation,
    y = I_like_that_people_use_Catalan)) + 
  geom_point() + 
  geom_boxplot()




```

```{r, I like it when people speak Spanish as a function of political orientation}

mod_null_like_use_Spanish <- lm(I_like_that_people_use_Spanish ~ 1, data = qp_data)

mod_1_like_use_Spanish <- lm(I_like_that_people_use_Spanish ~ 1 + political_orientation, data = qp_data)

mod_2_like_use_Spanish <- lm(I_like_that_people_use_Spanish ~ 1 + political_orientation + gender, data = qp_data)

mod_3_like_use_Spanish <- lm(I_like_that_people_use_Spanish ~ 1 + political_orientation + gender + age, data = qp_data)

mod_int_like_use_Spanish <- lm(I_like_that_people_use_Spanish ~ 1 + political_orientation + gender + age + political_orientation:gender:age, data = qp_data)

summary(mod_null_like_use_Spanish)
summary(mod_1_like_use_Spanish)
summary(mod_2_like_use_Spanish)
summary(mod_3_like_use_Spanish)
summary(mod_int_like_use_Spanish)

anova(mod_null_like_use_Spanish, mod_1_like_use_Spanish, mod_2_like_use_Spanish, mod_3_like_use_Spanish, mod_int_like_use_Spanish)

ggplot(
  data = qp_data, 
  aes(
    x = political_orientation,
    y = I_like_that_people_use_Spanish)) + 
  geom_point() + 
  geom_boxplot()


```

```{r, I like listening to Catalan as a function of political orientation}

mod_null_like_listen_Catalan <- lm(I_like_listening_to_Catalan ~ 1, data = qp_data)

mod_1_like_listen_Catalan <- lm(I_like_listening_to_Catalan ~ 1 + political_orientation, data = qp_data)

mod_2_like_listen_Catalan <- lm(I_like_listening_to_Catalan ~ 1 + political_orientation + gender, data = qp_data)

mod_3_like_listen_Catalan <- lm(I_like_listening_to_Catalan ~ 1 + political_orientation + gender + age, data = qp_data)

mod_int_like_listen_Catalan <- lm(I_like_listening_to_Catalan ~ 1 + political_orientation + gender + age + political_orientation:gender:age, data = qp_data)

summary(mod_null_like_listen_Catalan)
summary(mod_1_like_listen_Catalan)
summary(mod_2_like_listen_Catalan)
summary(mod_3_like_listen_Catalan)
summary(mod_int_like_listen_Catalan)

anova(mod_null_like_listen_Catalan, mod_1_like_listen_Catalan, mod_2_like_listen_Catalan, mod_3_like_listen_Catalan, mod_int_like_listen_Catalan)

ggplot(
  data = qp_data, 
  aes(
    x = political_orientation,
    y = I_like_listening_to_Catalan)) + 
  geom_point() + 
  geom_boxplot()



ggplot(
  data = qp_data, 
  aes(
    x = political_orientation,
    y = I_like_listening_to_Catalan, fill = political_orientation)) + 
  geom_point() + 
  #geom_boxplot() + 
  stat_summary(fun.data = mean_se, geom = "pointrange", pch = 23) +
  labs(x = "Political orientation", y = "I like listening to Catalan", fill = "Political Orientation") +
    scale_fill_manual(values = c("indianred2", "indianred2", "indianred2", "cornflowerblue", "cornflowerblue", "cornflowerblue"))


ggplot(
  data = qp_data, 
  aes(
    x = political_orientation,
    y = I_like_listening_to_Catalan, fill = political_orientation)) + 
  geom_point(size = 1) +
  stat_summary(fun.data = mean_se, geom = "pointrange", pch = 23, size = 1) +
  labs(x = "Political orientation", y = "I like listening to Catalan", fill = "Political Orientation") +
    scale_fill_manual(values = c("indianred2", "indianred2", "indianred2", "cornflowerblue", "cornflowerblue", "cornflowerblue"))


ggplot(
  data = qp_data, 
  aes(
    x = political_orientation,
    y = I_like_listening_to_Catalan, 
    fill = political_orientation)) + 
  geom_point(size = 1) +  # Set the size of the points on the plot
  stat_summary(fun.data = mean_se, geom = "pointrange", pch = 23, size = 1) +
  labs(x = "Political orientation", y = "I like listening to Catalan", fill = "Political Orientation") +
  scale_fill_manual(values = c("indianred2", "indianred2", "indianred2", "cornflowerblue", "cornflowerblue", "cornflowerblue")) +
  theme(
    legend.key.size = unit(1, "lines"),  # Set the size of the legend key
    legend.key.width = unit(1.5, "lines"),  # Set the width of the legend key
    legend.spacing.x = unit(0.5, "lines")  # Adjust spacing between legend items
  ) +
  guides(fill = guide_legend(override.aes = list(size = 0.5)))  # Set the size of points in the legend



```


```{r, I like listening to Spanish as a function of political orientation}

mod_null_like_listen_Spanish <- lm(I_like_listening_to_Spanish ~ 1, data = qp_data)

mod_1_like_listen_Spanish <- lm(I_like_listening_to_Spanish ~ 1 + political_orientation, data = qp_data)

mod_2_like_listen_Spanish <- lm(I_like_listening_to_Spanish ~ 1 + political_orientation + gender, data = qp_data)

mod_3_like_listen_Spanish <- lm(I_like_listening_to_Spanish ~ 1 + political_orientation + gender + age, data = qp_data)

mod_int_like_listen_Spanish <- lm(I_like_listening_to_Spanish ~ 1 + political_orientation + gender + age + political_orientation:gender:age, data = qp_data)



summary(mod_null_like_listen_Spanish)
summary(mod_1_like_listen_Spanish)
summary(mod_2_like_listen_Spanish)
summary(mod_3_like_listen_Spanish)
summary(mod_int_like_listen_Spanish)

anova(mod_null_like_listen_Spanish, mod_1_like_listen_Spanish, mod_2_like_listen_Spanish, mod_3_like_listen_Spanish, mod_int_like_listen_Spanish)

ggplot(
  data = qp_data, 
  aes(
    x = political_orientation,
    y = I_like_listening_to_Spanish)) + 
  geom_point() + 
  geom_boxplot()




ggplot(
  data = qp_data, 
  aes(
    x = political_orientation,
    y = I_like_listening_to_Spanish, 
    fill = political_orientation)) + 
  geom_point(size = 1) +  # Set the size of the points on the plot
  stat_summary(fun.data = mean_se, geom = "pointrange", pch = 23, size = 1) +
  labs(x = "Political orientation", y = "I like listening to Spanish", fill = "Political Orientation") +
  scale_fill_manual(values = c("indianred2", "indianred2", "indianred2", "cornflowerblue", "cornflowerblue", "cornflowerblue")) +
  theme(
    legend.key.size = unit(1, "lines"),  # Set the size of the legend key
    legend.key.width = unit(1.5, "lines"),  # Set the width of the legend key
    legend.spacing.x = unit(0.5, "lines")  # Adjust spacing between legend items
  ) +
  guides(fill = guide_legend(override.aes = list(size = 0.5)))  # Set the size of points in the legend


```

```{r, I like to use Catalan as a function of political orientation}

mod_null_I_like_to_use_Catalan <- lm(I_like_to_use_Catalan ~ 1, data = qp_data)

mod_1_I_like_to_use_Catalan <- lm(I_like_to_use_Catalan ~ 1 + political_orientation, data = qp_data)

mod_2_I_like_to_use_Catalan <- lm(I_like_to_use_Catalan ~ 1 + political_orientation + gender, data = qp_data)

mod_3_I_like_to_use_Catalan <- lm(I_like_to_use_Catalan ~ 1 + political_orientation + gender + age, data = qp_data)

mod_int_I_like_to_use_Catalan <- lm(I_like_to_use_Catalan ~ 1 + political_orientation + gender + age + political_orientation:gender:age, data = qp_data)

summary(mod_null_I_like_to_use_Catalan)
summary(mod_1_I_like_to_use_Catalan)
summary(mod_2_I_like_to_use_Catalan)
summary(mod_3_I_like_to_use_Catalan)
summary(mod_int_I_like_to_use_Catalan)

anova(mod_null_I_like_to_use_Catalan, mod_1_I_like_to_use_Catalan, mod_2_I_like_to_use_Catalan, mod_3_I_like_to_use_Catalan, mod_int_I_like_to_use_Catalan)

ggplot(
  data = qp_data, 
  aes(
    x = political_orientation,
    y = I_like_to_use_Catalan, fill = political_orientation)) + 
  geom_point() + 
  geom_boxplot() +
  labs(x = "Political orientation", y = "I like to use Catalan", fill = "Political Orientation") +
    scale_fill_manual(values = c("indianred2", "indianred2", "indianred2", "cornflowerblue", "cornflowerblue", "cornflowerblue"))


ggplot(
  data = qp_data, 
  aes(
    x = political_orientation,
    y = I_like_to_use_Catalan, 
    fill = political_orientation)) + 
  geom_point(size = 1) +  # Set the size of the points on the plot
  stat_summary(fun.data = mean_se, geom = "pointrange", pch = 23, size = 1) +
  labs(x = "Political orientation", y = "I like to use Catalan", fill = "Political Orientation") +
  scale_fill_manual(values = c("indianred2", "indianred2", "indianred2", "cornflowerblue", "cornflowerblue", "cornflowerblue")) +
  theme(
    legend.key.size = unit(1, "lines"),  # Set the size of the legend key
    legend.key.width = unit(1.5, "lines"),  # Set the width of the legend key
    legend.spacing.x = unit(0.5, "lines")  # Adjust spacing between legend items
  ) +
  guides(fill = guide_legend(override.aes = list(size = 0.5)))  # Set the size of points in the legend


```

```{r, I like to use Spanish as a function of political orientation}

mod_null_I_like_to_use_Spanish <- lm(I_like_to_use_Spanish ~ 1, data = qp_data)

mod_1_I_like_to_use_Spanish <- lm(I_like_to_use_Spanish ~ 1 + political_orientation, data = qp_data)

mod_2_I_like_to_use_Spanish <- lm(I_like_to_use_Spanish ~ 1 + political_orientation + gender, data = qp_data)

mod_3_I_like_to_use_Spanish <- lm(I_like_to_use_Spanish ~ 1 + political_orientation + gender + age, data = qp_data)

mod_int_I_like_to_use_Spanish <- lm(I_like_to_use_Spanish ~ 1 + political_orientation + gender + age + political_orientation:gender:age, data = qp_data)

summary(mod_null_I_like_to_use_Spanish)
summary(mod_1_I_like_to_use_Spanish)
summary(mod_2_I_like_to_use_Spanish)
summary(mod_3_I_like_to_use_Spanish)
summary(mod_int_I_like_to_use_Spanish)

anova(mod_null_I_like_to_use_Spanish, mod_1_I_like_to_use_Spanish, mod_2_I_like_to_use_Spanish, mod_3_I_like_to_use_Spanish, mod_int_I_like_to_use_Spanish)

ggplot(
  data = qp_data, 
  aes(
    x = political_orientation,
    y = I_like_to_use_Spanish)) + 
  geom_point() + 
  geom_boxplot()
```

```{r, Catalan is a difficult language to learn as a function of political orientation}

mod_null_Catalan_is_a_difficult_language_to_learn <- lm(Catalan_is_a_difficult_language_to_learn ~ 1, data = qp_data)

mod_1_Catalan_is_a_difficult_language_to_learn <- lm(Catalan_is_a_difficult_language_to_learn ~ 1 + political_orientation, data = qp_data)

mod_2_Catalan_is_a_difficult_language_to_learn <- lm(Catalan_is_a_difficult_language_to_learn ~ 1 + political_orientation + gender, data = qp_data)

mod_3_Catalan_is_a_difficult_language_to_learn <- lm(Catalan_is_a_difficult_language_to_learn ~ 1 + political_orientation + gender + age, data = qp_data)

mod_int_Catalan_is_a_difficult_language_to_learn <- lm(Catalan_is_a_difficult_language_to_learn ~ 1 + political_orientation + gender + age + political_orientation:gender:age, data = qp_data)

summary(mod_null_Catalan_is_a_difficult_language_to_learn)
summary(mod_1_Catalan_is_a_difficult_language_to_learn)
summary(mod_2_Catalan_is_a_difficult_language_to_learn)
summary(mod_3_Catalan_is_a_difficult_language_to_learn)
summary(mod_int_Catalan_is_a_difficult_language_to_learn)

anova(mod_null_Catalan_is_a_difficult_language_to_learn, mod_1_Catalan_is_a_difficult_language_to_learn, mod_2_Catalan_is_a_difficult_language_to_learn, mod_3_Catalan_is_a_difficult_language_to_learn, mod_int_Catalan_is_a_difficult_language_to_learn)

ggplot(
  data = qp_data, 
  aes(
    x = political_orientation,
    y = Catalan_is_a_difficult_language_to_learn)) + 
  geom_point() + 
  geom_boxplot()


```

```{r}
# Sample data
df <- data.frame(original_column = c(1, 2, 3, 4, 5))

# Rename the column
names(qp_data)[names(qp_data) == "Spanish _is_a_difficult_language_to_learn"] <- "Spanish_is_a_difficult_language_to_learn"

# Display the modified data frame
print(df)

```


```{r, Spanish is a difficult language to learn as a function of political orientation}

mod_null_Spanish_is_a_difficult_language_to_learn <- lm(Spanish_is_a_difficult_language_to_learn ~ 1, data = qp_data)

mod_1_Spanish_is_a_difficult_language_to_learn <- lm(Spanish_is_a_difficult_language_to_learn ~ 1 + political_orientation, data = qp_data)

mod_2_Spanish_is_a_difficult_language_to_learn <- lm(Spanish_is_a_difficult_language_to_learn ~ 1 + political_orientation + gender, data = qp_data)

mod_3_Spanish_is_a_difficult_language_to_learn <- lm(Spanish_is_a_difficult_language_to_learn ~ 1 + political_orientation + gender + age, data = qp_data)

mod_int_Spanish_is_a_difficult_language_to_learn <- lm(Spanish_is_a_difficult_language_to_learn ~ 1 + political_orientation + gender + age + political_orientation:gender:age, data = qp_data)

summary(mod_null_Spanish_is_a_difficult_language_to_learn)
summary(mod_1_Spanish_is_a_difficult_language_to_learn)
summary(mod_2_Spanish_is_a_difficult_language_to_learn)
summary(mod_3_Spanish_is_a_difficult_language_to_learn)
summary(mod_int_Spanish_is_a_difficult_language_to_learn)

anova(mod_null_Spanish_is_a_difficult_language_to_learn, mod_1_Spanish_is_a_difficult_language_to_learn, mod_2_Spanish_is_a_difficult_language_to_learn, mod_3_Spanish_is_a_difficult_language_to_learn, mod_int_Spanish_is_a_difficult_language_to_learn)

ggplot(
  data = qp_data, 
  aes(
    x = political_orientation,
    y = Spanish_is_a_difficult_language_to_learn, fill = political_orientation)) + 
  geom_point() + 
  geom_boxplot() +
  labs(x = "Political orientation", y = "Spanish is a difficult language to learn", fill = "Political Orientation") +
    scale_fill_manual(values = c("indianred2", "indianred2", "indianred2", "cornflowerblue", "cornflowerblue", "cornflowerblue"))

```

```{r, Catalan is a beautiful language}

mod_null_Catalan_is_a_beautiful_language<- lm(Catalan_is_a_beautiful_language ~ 1, data = qp_data)

mod_1_Catalan_is_a_beautiful_language <- lm(Catalan_is_a_beautiful_language ~ 1 + political_orientation, data = qp_data)

mod_2_Catalan_is_a_beautiful_language <- lm(Catalan_is_a_beautiful_language ~ 1 + political_orientation + gender, data = qp_data)

mod_3_Catalan_is_a_beautiful_language <- lm(Catalan_is_a_beautiful_language ~ 1 + political_orientation + gender + age, data = qp_data)

mod_int_Catalan_is_a_beautiful_language <- lm(Catalan_is_a_beautiful_language ~ 1 + political_orientation + gender + age + political_orientation:gender:age, data = qp_data)

summary(mod_null_Catalan_is_a_beautiful_language)
summary(mod_1_Catalan_is_a_beautiful_language)
summary(mod_2_Catalan_is_a_beautiful_language)
summary(mod_3_Catalan_is_a_beautiful_language)
summary(mod_int_Catalan_is_a_beautiful_language)

anova(mod_null_Catalan_is_a_beautiful_language, mod_1_Catalan_is_a_beautiful_language, mod_2_Catalan_is_a_beautiful_language, mod_3_Catalan_is_a_beautiful_language, mod_int_Catalan_is_a_beautiful_language)

ggplot(
  data = qp_data, 
  aes(
    x = political_orientation,
    y = Catalan_is_a_beautiful_language, fill = political_orientation)) + 
  geom_point() + 
  geom_boxplot() +
  labs(x = "Political orientation", y = "Catalan is a beautiful language", fill = "Political Orientation") +
    scale_fill_manual(values = c("indianred2", "indianred2", "indianred2", "cornflowerblue", "cornflowerblue", "cornflowerblue"))



ggplot(
  data = qp_data, 
  aes(
    x = political_orientation,
    y = Catalan_is_a_beautiful_language, 
    fill = political_orientation)) + 
  geom_point(size = 1) +  # Set the size of the points on the plot
  stat_summary(fun.data = mean_se, geom = "pointrange", pch = 23, size = 1) +
  labs(x = "Political orientation", y = "Catalan is a beautiful language", fill = "Political Orientation") +
  scale_fill_manual(values = c("indianred2", "indianred2", "indianred2", "cornflowerblue", "cornflowerblue", "cornflowerblue")) +
  theme(
    legend.key.size = unit(1, "lines"),  # Set the size of the legend key
    legend.key.width = unit(1.5, "lines"),  # Set the width of the legend key
    legend.spacing.x = unit(0.5, "lines")  # Adjust spacing between legend items
  ) +
  guides(fill = guide_legend(override.aes = list(size = 0.5)))  # Set the size of points in the legend



```

```{r, Spanish is a beautiful language as a function of political orientation}

mod_null_Spanish_is_a_beautiful_language<- lm(Spanish_is_a_beautiful_language ~ 1, data = qp_data)

mod_1_Spanish_is_a_beautiful_language <- lm(Spanish_is_a_beautiful_language ~ 1 + political_orientation, data = qp_data)

mod_2_Spanish_is_a_beautiful_language <- lm(Spanish_is_a_beautiful_language ~ 1 + political_orientation + gender, data = qp_data)

mod_3_Spanish_is_a_beautiful_language <- lm(Spanish_is_a_beautiful_language ~ 1 + political_orientation + gender + age, data = qp_data)

mod_int_Spanish_is_a_beautiful_language <- lm(Spanish_is_a_beautiful_language ~ 1 + political_orientation + gender + age + political_orientation:gender:age, data = qp_data)

summary(mod_null_Spanish_is_a_beautiful_language)
summary(mod_1_Spanish_is_a_beautiful_language)
summary(mod_2_Spanish_is_a_beautiful_language)
summary(mod_3_Spanish_is_a_beautiful_language)
summary(mod_int_Spanish_is_a_beautiful_language)

anova(mod_null_Spanish_is_a_beautiful_language, mod_1_Spanish_is_a_beautiful_language, mod_2_Spanish_is_a_beautiful_language, mod_3_Spanish_is_a_beautiful_language, mod_int_Spanish_is_a_beautiful_language)

ggplot(
  data = qp_data, 
  aes(
    x = political_orientation,
    y = Spanish_is_a_beautiful_language)) + 
  geom_point() + 
  geom_boxplot()
```


```{r, I try to use Catalan whenever I can as a function of political orientation}

mod_null_I_try_to_use_Catalan_whenever_I_can <- lm(I_try_to_use_Catalan_whenever_I_can ~ 1, data = qp_data)

mod_1_I_try_to_use_Catalan_whenever_I_can <- lm(I_try_to_use_Catalan_whenever_I_can ~ 1 + political_orientation, data = qp_data)

mod_2_I_try_to_use_Catalan_whenever_I_can <- lm(I_try_to_use_Catalan_whenever_I_can ~ 1 + political_orientation + gender, data = qp_data)

mod_3_I_try_to_use_Catalan_whenever_I_can <- lm(I_try_to_use_Catalan_whenever_I_can ~ 1 + political_orientation + gender + age, data = qp_data)

mod_int_I_try_to_use_Catalan_whenever_I_can <- lm(I_try_to_use_Catalan_whenever_I_can ~ 1 + political_orientation + gender + age + political_orientation:gender:age, data = qp_data)

summary(mod_null_I_try_to_use_Catalan_whenever_I_can)
summary(mod_1_I_try_to_use_Catalan_whenever_I_can)
summary(mod_2_I_try_to_use_Catalan_whenever_I_can)
summary(mod_3_I_try_to_use_Catalan_whenever_I_can)
summary(mod_int_I_try_to_use_Catalan_whenever_I_can)

anova(mod_null_I_try_to_use_Catalan_whenever_I_can, mod_1_I_try_to_use_Catalan_whenever_I_can, mod_2_I_try_to_use_Catalan_whenever_I_can, mod_3_I_try_to_use_Catalan_whenever_I_can, mod_int_I_try_to_use_Catalan_whenever_I_can)

ggplot(
  data = qp_data, 
  aes(
    x = political_orientation,
    y = I_try_to_use_Catalan_whenever_I_can, fill = political_orientation)) + 
  geom_point() + 
  geom_boxplot() +
  labs(x = "Political orientation", y = "I try to use Catalan whenever I can", fill = "Political Orientation") +
    scale_fill_manual(values = c("indianred2", "indianred2", "indianred2", "cornflowerblue", "cornflowerblue", "cornflowerblue"))


ggplot(
  data = qp_data, 
  aes(
    x = political_orientation,
    y = I_try_to_use_Catalan_whenever_I_can, 
    fill = political_orientation)) + 
  geom_point(size = 1) +  # Set the size of the points on the plot
  stat_summary(fun.data = mean_se, geom = "pointrange", pch = 23, size = 1) +
  labs(x = "Political orientation", y = "I try to use Catalan whenever I can", fill = "Political Orientation") +
  scale_fill_manual(values = c("indianred2", "indianred2", "indianred2", "cornflowerblue", "cornflowerblue", "cornflowerblue")) +
  theme(
    legend.key.size = unit(1, "lines"),  # Set the size of the legend key
    legend.key.width = unit(1.5, "lines"),  # Set the width of the legend key
    legend.spacing.x = unit(0.5, "lines")  # Adjust spacing between legend items
  ) +
  guides(fill = guide_legend(override.aes = list(size = 0.5)))  # Set the size of points in the legend



```


```{r, I try to use Spanish whenever I can as a function of political orientation}

mod_null_I_try_to_use_Spanish_whenever_I_can <- lm(I_try_to_use_Spanish_whenever_I_can ~ 1, data = qp_data)

mod_1_I_try_to_use_Spanish_whenever_I_can <- lm(I_try_to_use_Spanish_whenever_I_can ~ 1 + political_orientation, data = qp_data)

mod_2_I_try_to_use_Spanish_whenever_I_can <- lm(I_try_to_use_Spanish_whenever_I_can ~ 1 + political_orientation + gender, data = qp_data)

mod_3_I_try_to_use_Spanish_whenever_I_can <- lm(I_try_to_use_Spanish_whenever_I_can ~ 1 + political_orientation + gender + age, data = qp_data)

mod_int_I_try_to_use_Spanish_whenever_I_can <- lm(I_try_to_use_Spanish_whenever_I_can ~ 1 + political_orientation + gender + age + political_orientation:gender:age, data = qp_data)

summary(mod_null_I_try_to_use_Spanish_whenever_I_can)
summary(mod_1_I_try_to_use_Spanish_whenever_I_can)
summary(mod_2_I_try_to_use_Spanish_whenever_I_can)
summary(mod_3_I_try_to_use_Spanish_whenever_I_can)
summary(mod_int_I_try_to_use_Spanish_whenever_I_can)

anova(mod_null_I_try_to_use_Spanish_whenever_I_can, mod_1_I_try_to_use_Spanish_whenever_I_can, mod_2_I_try_to_use_Spanish_whenever_I_can, mod_3_I_try_to_use_Spanish_whenever_I_can, mod_int_I_try_to_use_Spanish_whenever_I_can)

ggplot(
  data = qp_data, 
  aes(
    x = political_orientation,
    y = I_try_to_use_Spanish_whenever_I_can, fill = political_orientation)) + 
  geom_point() + 
  geom_boxplot() +
  labs(x = "Political orientation", y = "I try to use Spanish whenever I can", fill = "Political Orientation") +
    scale_fill_manual(values = c("indianred2", "indianred2", "indianred2", "cornflowerblue", "cornflowerblue", "cornflowerblue"))


ggplot(
  data = qp_data, 
  aes(
    x = political_orientation,
    y = I_try_to_use_Spanish_whenever_I_can, 
    fill = political_orientation)) + 
  geom_point(size = 1) +  # Set the size of the points on the plot
  stat_summary(fun.data = mean_se, geom = "pointrange", pch = 23, size = 1) +
  labs(x = "Political orientation", y = "I try to use Spanish whenever I can", fill = "Political Orientation") +
  scale_fill_manual(values = c("indianred2", "indianred2", "indianred2", "cornflowerblue", "cornflowerblue", "cornflowerblue")) +
  theme(
    legend.key.size = unit(1, "lines"),  # Set the size of the legend key
    legend.key.width = unit(1.5, "lines"),  # Set the width of the legend key
    legend.spacing.x = unit(0.5, "lines")  # Adjust spacing between legend items
  ) +
  guides(fill = guide_legend(override.aes = list(size = 0.5)))  # Set the size of points in the legend


```

```{r, It is worth learning Catalan}

mod_null_It_is_worth_learning_Catalan <- lm(It_is_worth_learning_Catalan ~ 1, data = qp_data)

mod_1_It_is_worth_learning_Catalan <- lm(It_is_worth_learning_Catalan ~ 1 + political_orientation, data = qp_data)

mod_2_It_is_worth_learning_Catalan <- lm(It_is_worth_learning_Catalan ~ 1 + political_orientation + gender, data = qp_data)

mod_3_It_is_worth_learning_Catalan <- lm(It_is_worth_learning_Catalan ~ 1 + political_orientation + gender + age, data = qp_data)

mod_int_It_is_worth_learning_Catalan <- lm(It_is_worth_learning_Catalan ~ 1 + political_orientation + gender + age + political_orientation:gender:age, data = qp_data)

summary(mod_null_It_is_worth_learning_Catalan)
summary(mod_1_It_is_worth_learning_Catalan)
summary(mod_2_It_is_worth_learning_Catalan)
summary(mod_3_It_is_worth_learning_Catalan)
summary(mod_int_It_is_worth_learning_Catalan)

anova(mod_null_It_is_worth_learning_Catalan, mod_1_It_is_worth_learning_Catalan, mod_2_It_is_worth_learning_Catalan, mod_3_It_is_worth_learning_Catalan, mod_int_It_is_worth_learning_Catalan)

ggplot(
  data = qp_data, 
  aes(
    x = political_orientation,
    y = It_is_worth_learning_Catalan)) + 
  geom_point() + 
  geom_boxplot()

ggplot(
  data = qp_data, 
  aes(
    x = political_orientation,
    y = It_is_worth_learning_Catalan, 
    fill = political_orientation)) + 
  geom_point(size = 1) +  # Set the size of the points on the plot
  stat_summary(fun.data = mean_se, geom = "pointrange", pch = 23, size = 1) +
  labs(x = "Political orientation", y = "It is worth learning Catalan", fill = "Political Orientation") +
  scale_fill_manual(values = c("indianred2", "indianred2", "indianred2", "cornflowerblue", "cornflowerblue", "cornflowerblue")) +
  theme(
    legend.key.size = unit(1, "lines"),  # Set the size of the legend key
    legend.key.width = unit(1.5, "lines"),  # Set the width of the legend key
    legend.spacing.x = unit(0.5, "lines")  # Adjust spacing between legend items
  ) +
  guides(fill = guide_legend(override.aes = list(size = 0.5)))  # Set the size of points in the legend
```

```{r, It is worth learning Spanish as a function of political orientation}

mod_null_It_is_worth_learning_Spanish <- lm(It_is_worth_learning_Spanish ~ 1, data = qp_data)

mod_1_It_is_worth_learning_Spanish <- lm(It_is_worth_learning_Spanish ~ 1 + political_orientation, data = qp_data)

mod_2_It_is_worth_learning_Spanish <- lm(It_is_worth_learning_Spanish ~ 1 + political_orientation + gender, data = qp_data)

mod_3_It_is_worth_learning_Spanish <- lm(It_is_worth_learning_Spanish ~ 1 + political_orientation + gender + age, data = qp_data)

mod_int_It_is_worth_learning_Spanish <- lm(It_is_worth_learning_Spanish ~ 1 + political_orientation + gender + age + political_orientation:gender:age, data = qp_data)

summary(mod_null_It_is_worth_learning_Spanish)
summary(mod_1_It_is_worth_learning_Spanish)
summary(mod_2_It_is_worth_learning_Spanish)
summary(mod_3_It_is_worth_learning_Spanish)
summary(mod_int_It_is_worth_learning_Spanish)

anova(mod_null_It_is_worth_learning_Spanish, mod_1_It_is_worth_learning_Spanish, mod_2_It_is_worth_learning_Spanish, mod_3_It_is_worth_learning_Spanish, mod_int_It_is_worth_learning_Spanish)

ggplot(
  data = qp_data, 
  aes(
    x = political_orientation,
    y = It_is_worth_learning_Spanish, fill = political_orientation)) + 
  geom_point() + 
  geom_boxplot() +
  labs(x = "Political orientation", y = "It is worth learning Spanish", fill = "Political Orientation") +
    scale_fill_manual(values = c("indianred2", "indianred2", "indianred2", "cornflowerblue", "cornflowerblue", "cornflowerblue"))


```

```{r, Catalan is in danger of disappearing in the Balearic Islands}

mod_null_Catalan_is_in_danger_of_disappearing_in_the_Balearic_Islands <- lm(Catalan_is_in_danger_of_disappearing_in_the_Balearic_Islands ~ 1, data = qp_data)

mod_1_Catalan_is_in_danger_of_disappearing_in_the_Balearic_Islands <- lm(Catalan_is_in_danger_of_disappearing_in_the_Balearic_Islands ~ 1 + political_orientation, data = qp_data)

mod_2_Catalan_is_in_danger_of_disappearing_in_the_Balearic_Islands <- lm(Catalan_is_in_danger_of_disappearing_in_the_Balearic_Islands ~ 1 + political_orientation + gender, data = qp_data)

mod_3_Catalan_is_in_danger_of_disappearing_in_the_Balearic_Islands <- lm(Catalan_is_in_danger_of_disappearing_in_the_Balearic_Islands ~ 1 + political_orientation + gender + age, data = qp_data)

mod_int_Catalan_is_in_danger_of_disappearing_in_the_Balearic_Islands <- lm(Catalan_is_in_danger_of_disappearing_in_the_Balearic_Islands ~ 1 + political_orientation + gender + age + political_orientation:gender:age, data = qp_data)

summary(mod_null_Catalan_is_in_danger_of_disappearing_in_the_Balearic_Islands)
summary(mod_1_Catalan_is_in_danger_of_disappearing_in_the_Balearic_Islands)
summary(mod_2_Catalan_is_in_danger_of_disappearing_in_the_Balearic_Islands)
summary(mod_3_Catalan_is_in_danger_of_disappearing_in_the_Balearic_Islands)
summary(mod_int_Catalan_is_in_danger_of_disappearing_in_the_Balearic_Islands)

anova(mod_null_Catalan_is_in_danger_of_disappearing_in_the_Balearic_Islands, mod_1_Catalan_is_in_danger_of_disappearing_in_the_Balearic_Islands, mod_2_Catalan_is_in_danger_of_disappearing_in_the_Balearic_Islands, mod_3_Catalan_is_in_danger_of_disappearing_in_the_Balearic_Islands, mod_int_Catalan_is_in_danger_of_disappearing_in_the_Balearic_Islands)

ggplot(
  data = qp_data, 
  aes(
    x = political_orientation,
    y = Catalan_is_in_danger_of_disappearing_in_the_Balearic_Islands, fill = political_orientation)) + 
  geom_point() + 
  geom_boxplot() +
  labs(x = "Political orientation", y = "Catalan is in danger of disappearing in the Balearic Islands", fill = "Political Orientation") +
    scale_fill_manual(values = c("indianred2", "indianred2", "indianred2", "cornflowerblue", "cornflowerblue", "cornflowerblue"))



ggplot(
  data = qp_data, 
  aes(
    x = political_orientation,
    y = Catalan_is_in_danger_of_disappearing_in_the_Balearic_Islands, 
    fill = political_orientation)) + 
  geom_point(size = 1) +  # Set the size of the points on the plot
  stat_summary(fun.data = mean_se, geom = "pointrange", pch = 23, size = 1) +
  labs(x = "Political orientation", y = "Catalan is in danger in the Balearic Islands", fill = "Political Orientation") +
  scale_fill_manual(values = c("indianred2", "indianred2", "indianred2", "cornflowerblue", "cornflowerblue", "cornflowerblue")) +
  theme(
    legend.key.size = unit(1, "lines"),  # Set the size of the legend key
    legend.key.width = unit(1.5, "lines"),  # Set the width of the legend key
    legend.spacing.x = unit(0.5, "lines")  # Adjust spacing between legend items
  ) +
  guides(fill = guide_legend(override.aes = list(size = 0.5)))  # Set the size of points in the legend

```

```{r, Spanish is in danger of disappearing in the Balearic Islands}

mod_null_Spanish_is_in_danger_of_disappearing_in_the_Balearic_Islands <- lm(Spanish_is_in_danger_of_disappearing_in_the_Balearic_Islands ~ 1, data = qp_data)

mod_1_Spanish_is_in_danger_of_disappearing_in_the_Balearic_Islands <- lm(Spanish_is_in_danger_of_disappearing_in_the_Balearic_Islands ~ 1 + political_orientation, data = qp_data)

mod_2_Spanish_is_in_danger_of_disappearing_in_the_Balearic_Islands <- lm(Spanish_is_in_danger_of_disappearing_in_the_Balearic_Islands ~ 1 + political_orientation + gender, data = qp_data)

mod_3_Spanish_is_in_danger_of_disappearing_in_the_Balearic_Islands <- lm(Spanish_is_in_danger_of_disappearing_in_the_Balearic_Islands ~ 1 + political_orientation + gender + age, data = qp_data)

mod_int_Spanish_is_in_danger_of_disappearing_in_the_Balearic_Islands <- lm(Spanish_is_in_danger_of_disappearing_in_the_Balearic_Islands ~ 1 + political_orientation + gender + age + political_orientation:gender:age, data = qp_data)

summary(mod_null_Spanish_is_in_danger_of_disappearing_in_the_Balearic_Islands)
summary(mod_1_Spanish_is_in_danger_of_disappearing_in_the_Balearic_Islands)
summary(mod_2_Spanish_is_in_danger_of_disappearing_in_the_Balearic_Islands)
summary(mod_3_Spanish_is_in_danger_of_disappearing_in_the_Balearic_Islands)
summary(mod_int_Spanish_is_in_danger_of_disappearing_in_the_Balearic_Islands)

anova(mod_null_Spanish_is_in_danger_of_disappearing_in_the_Balearic_Islands, mod_1_Spanish_is_in_danger_of_disappearing_in_the_Balearic_Islands, mod_2_Spanish_is_in_danger_of_disappearing_in_the_Balearic_Islands, mod_3_Spanish_is_in_danger_of_disappearing_in_the_Balearic_Islands, mod_int_Spanish_is_in_danger_of_disappearing_in_the_Balearic_Islands)

ggplot(
  data = qp_data, 
  aes(
    x = political_orientation,
    y = Spanish_is_in_danger_of_disappearing_in_the_Balearic_Islands)) + 
  geom_point() + 
  geom_boxplot()

```

```{r, No language is more important than the other political orientation}

mod_null_No_language_is_more_important_than_the_other <- lm(No_language_is_more_important_than_the_other ~ 1, data = qp_data)

mod_1_No_language_is_more_important_than_the_other <- lm(No_language_is_more_important_than_the_other ~ 1 + political_orientation, data = qp_data)

mod_2_No_language_is_more_important_than_the_other <- lm(No_language_is_more_important_than_the_other ~ 1 + political_orientation + gender, data = qp_data)

mod_3_No_language_is_more_important_than_the_other <- lm(No_language_is_more_important_than_the_other ~ 1 + political_orientation + gender + age, data = qp_data)

mod_int_No_language_is_more_important_than_the_other <- lm(No_language_is_more_important_than_the_other ~ 1 + political_orientation + gender + age + political_orientation:gender:age, data = qp_data)

summary(mod_null_No_language_is_more_important_than_the_other)
summary(mod_1_No_language_is_more_important_than_the_other)
summary(mod_2_No_language_is_more_important_than_the_other)
summary(mod_3_No_language_is_more_important_than_the_other)
summary(mod_int_No_language_is_more_important_than_the_other)

anova(mod_null_No_language_is_more_important_than_the_other, mod_1_No_language_is_more_important_than_the_other, mod_2_No_language_is_more_important_than_the_other, mod_3_No_language_is_more_important_than_the_other, mod_int_No_language_is_more_important_than_the_other)

ggplot(
  data = qp_data, 
  aes(
    x = political_orientation,
    y = No_language_is_more_important_than_the_other)) + 
  geom_point() + 
  geom_boxplot()


```

```{r, Catalan can become an important language in the European context}

mod_null_Catalan_can_become_an_important_language_in_the_European_context <- lm(Catalan_can_become_an_important_language_in_the_European_context ~ 1, data = qp_data)

mod_1_Catalan_can_become_an_important_language_in_the_European_context <- lm(Catalan_can_become_an_important_language_in_the_European_context ~ 1 + political_orientation, data = qp_data)

mod_2_Catalan_can_become_an_important_language_in_the_European_context <- lm(Catalan_can_become_an_important_language_in_the_European_context ~ 1 + political_orientation + gender, data = qp_data)

mod_3_Catalan_can_become_an_important_language_in_the_European_context <- lm(Catalan_can_become_an_important_language_in_the_European_context ~ 1 + political_orientation + gender + age, data = qp_data)

mod_int_Catalan_can_become_an_important_language_in_the_European_context <- lm(Catalan_can_become_an_important_language_in_the_European_context ~ 1 + political_orientation + gender + age + political_orientation:gender:age, data = qp_data)

summary(mod_null_Catalan_can_become_an_important_language_in_the_European_context)
summary(mod_1_Catalan_can_become_an_important_language_in_the_European_context)
summary(mod_2_Catalan_can_become_an_important_language_in_the_European_context)
summary(mod_3_Catalan_can_become_an_important_language_in_the_European_context)
summary(mod_int_Catalan_can_become_an_important_language_in_the_European_context)

anova(mod_null_Catalan_can_become_an_important_language_in_the_European_context, mod_1_Catalan_can_become_an_important_language_in_the_European_context, mod_2_Catalan_can_become_an_important_language_in_the_European_context, mod_3_Catalan_can_become_an_important_language_in_the_European_context, mod_int_Catalan_can_become_an_important_language_in_the_European_context)

ggplot(
  data = qp_data, 
  aes(
    x = political_orientation,
    y = Catalan_can_become_an_important_language_in_the_European_context)) + 
  geom_point() + 
  geom_boxplot()


ggplot(
  data = qp_data, 
  aes(
    x = political_orientation,
    y = Catalan_can_become_an_important_language_in_the_European_context, 
    fill = political_orientation)) + 
  geom_point(size = 1) +  # Set the size of the points on the plot
  stat_summary(fun.data = mean_se, geom = "pointrange", pch = 23, size = 1) +
  labs(x = "Political orientation", y = "Catalan can be important in the European context", fill = "Political Orientation") +
  scale_fill_manual(values = c("indianred2", "indianred2", "indianred2", "cornflowerblue", "cornflowerblue", "cornflowerblue")) +
  theme(
    legend.key.size = unit(1, "lines"),  # Set the size of the legend key
    legend.key.width = unit(1.5, "lines"),  # Set the width of the legend key
    legend.spacing.x = unit(0.5, "lines")  # Adjust spacing between legend items
  ) +
  guides(fill = guide_legend(override.aes = list(size = 0.5)))  # Set the size of points in the legend


```

```{r, Spanish can become an important language in the European context}

mod_null_Spanish_can_become_an_important_language_in_the_European_context <- lm(Spanish_can_become_an_important_language_in_the_European_context ~ 1, data = qp_data)

mod_1_Spanish_can_become_an_important_language_in_the_European_context <- lm(Spanish_can_become_an_important_language_in_the_European_context ~ 1 + political_orientation, data = qp_data)

mod_2_Spanish_can_become_an_important_language_in_the_European_context <- lm(Spanish_can_become_an_important_language_in_the_European_context ~ 1 + political_orientation + gender, data = qp_data)

mod_3_Spanish_can_become_an_important_language_in_the_European_context <- lm(Spanish_can_become_an_important_language_in_the_European_context ~ 1 + political_orientation + gender + age, data = qp_data)

mod_int_Spanish_can_become_an_important_language_in_the_European_context <- lm(Spanish_can_become_an_important_language_in_the_European_context ~ 1 + political_orientation + gender + age + political_orientation:gender:age, data = qp_data)

summary(mod_null_Spanish_can_become_an_important_language_in_the_European_context)
summary(mod_1_Spanish_can_become_an_important_language_in_the_European_context)
summary(mod_2_Spanish_can_become_an_important_language_in_the_European_context)
summary(mod_3_Spanish_can_become_an_important_language_in_the_European_context)
summary(mod_int_Spanish_can_become_an_important_language_in_the_European_context)

anova(mod_null_Spanish_can_become_an_important_language_in_the_European_context, mod_1_Spanish_can_become_an_important_language_in_the_European_context, mod_2_Spanish_can_become_an_important_language_in_the_European_context, mod_3_Spanish_can_become_an_important_language_in_the_European_context, mod_int_Spanish_can_become_an_important_language_in_the_European_context)

ggplot(
  data = qp_data, 
  aes(
    x = political_orientation,
    y = Spanish_can_become_an_important_language_in_the_European_context)) + 
  geom_point() + 
  geom_boxplot()

```


```{r, Sometimes I feel compelled to use Catalan}

mod_null_Sometimes_I_feel_compelled_to_use_Catalan <- lm(Sometimes_I_feel_compelled_to_use_Catalan ~ 1, data = qp_data)

mod_1_Sometimes_I_feel_compelled_to_use_Catalan <- lm(Sometimes_I_feel_compelled_to_use_Catalan ~ 1 + political_orientation, data = qp_data)

mod_2_Sometimes_I_feel_compelled_to_use_Catalan <- lm(Sometimes_I_feel_compelled_to_use_Catalan ~ 1 + political_orientation + gender, data = qp_data)

mod_3_Sometimes_I_feel_compelled_to_use_Catalan <- lm(Sometimes_I_feel_compelled_to_use_Catalan ~ 1 + political_orientation + gender + age, data = qp_data)

mod_int_Sometimes_I_feel_compelled_to_use_Catalan <- lm(Sometimes_I_feel_compelled_to_use_Catalan ~ 1 + political_orientation + gender + age + political_orientation:gender:age, data = qp_data)

summary(mod_null_Sometimes_I_feel_compelled_to_use_Catalan)
summary(mod_1_Sometimes_I_feel_compelled_to_use_Catalan)
summary(mod_2_Sometimes_I_feel_compelled_to_use_Catalan)
summary(mod_3_Sometimes_I_feel_compelled_to_use_Catalan)
summary(mod_int_Sometimes_I_feel_compelled_to_use_Catalan)

anova(mod_null_Sometimes_I_feel_compelled_to_use_Catalan, mod_1_Sometimes_I_feel_compelled_to_use_Catalan, mod_2_Sometimes_I_feel_compelled_to_use_Catalan, mod_3_Sometimes_I_feel_compelled_to_use_Catalan, mod_int_Sometimes_I_feel_compelled_to_use_Catalan)

ggplot(
  data = qp_data, 
  aes(
    x = political_orientation,
    y = Sometimes_I_feel_compelled_to_use_Catalan)) + 
  geom_point() + 
  geom_boxplot()


```

```{r, Sometimes I feel compelled to use Spanish}

mod_null_Sometimes_I_feel_compelled_to_use_Spanish <- lm(Sometimes_I_feel_compelled_to_use_Spanish ~ 1, data = qp_data)

mod_1_Sometimes_I_feel_compelled_to_use_Spanish <- lm(Sometimes_I_feel_compelled_to_use_Spanish ~ 1 + political_orientation, data = qp_data)

mod_2_Sometimes_I_feel_compelled_to_use_Spanish <- lm(Sometimes_I_feel_compelled_to_use_Spanish ~ 1 + political_orientation + gender, data = qp_data)

mod_3_Sometimes_I_feel_compelled_to_use_Spanish <- lm(Sometimes_I_feel_compelled_to_use_Spanish ~ 1 + political_orientation + gender + age, data = qp_data)

mod_int_Sometimes_I_feel_compelled_to_use_Spanish <- lm(Sometimes_I_feel_compelled_to_use_Spanish ~ 1 + political_orientation + gender + age + political_orientation:gender:age, data = qp_data)

summary(mod_null_Sometimes_I_feel_compelled_to_use_Spanish)
summary(mod_1_Sometimes_I_feel_compelled_to_use_Spanish)
summary(mod_2_Sometimes_I_feel_compelled_to_use_Spanish)
summary(mod_3_Sometimes_I_feel_compelled_to_use_Spanish)
summary(mod_int_Sometimes_I_feel_compelled_to_use_Spanish)

anova(mod_null_Sometimes_I_feel_compelled_to_use_Spanish, mod_1_Sometimes_I_feel_compelled_to_use_Spanish, mod_2_Sometimes_I_feel_compelled_to_use_Spanish, mod_3_Sometimes_I_feel_compelled_to_use_Spanish, mod_int_Sometimes_I_feel_compelled_to_use_Spanish)

ggplot(
  data = qp_data, 
  aes(
    x = political_orientation,
    y = Sometimes_I_feel_compelled_to_use_Spanish, fill = political_orientation)) + 
  geom_point() + 
  geom_boxplot() +
  labs(x = "Political orientation", y = "Sometimes I feel compelled to use Spanish", fill = "Political Orientation") +
    scale_fill_manual(values = c("indianred2", "indianred2", "indianred2", "cornflowerblue", "cornflowerblue", "cornflowerblue"))


ggplot(
  data = qp_data, 
  aes(
    x = political_orientation,
    y = Sometimes_I_feel_compelled_to_use_Spanish, 
    fill = political_orientation)) + 
  geom_point(size = 1) +  # Set the size of the points on the plot
  stat_summary(fun.data = mean_se, geom = "pointrange", pch = 23, size = 1) +
  labs(x = "Political orientation", y = "Sometimes I feel compelled to use Spanish", fill = "Political Orientation") +
  scale_fill_manual(values = c("indianred2", "indianred2", "indianred2", "cornflowerblue", "cornflowerblue", "cornflowerblue")) +
  theme(
    legend.key.size = unit(1, "lines"),  # Set the size of the legend key
    legend.key.width = unit(1.5, "lines"),  # Set the width of the legend key
    legend.spacing.x = unit(0.5, "lines")  # Adjust spacing between legend items
  ) +
  guides(fill = guide_legend(override.aes = list(size = 0.5)))  # Set the size of points in the legend



```

```{r, It is unpleasant to learn Catalan}

mod_null_It_is_unpleasant_to_learn_Catalan <- lm(It_is_unpleasant_to_learn_Catalan ~ 1, data = qp_data)

mod_1_It_is_unpleasant_to_learn_Catalan <- lm(It_is_unpleasant_to_learn_Catalan ~ 1 + political_orientation, data = qp_data)

mod_2_It_is_unpleasant_to_learn_Catalan <- lm(It_is_unpleasant_to_learn_Catalan ~ 1 + political_orientation + gender, data = qp_data)

mod_3_It_is_unpleasant_to_learn_Catalan <- lm(It_is_unpleasant_to_learn_Catalan ~ 1 + political_orientation + gender + age, data = qp_data)

mod_int_It_is_unpleasant_to_learn_Catalan <- lm(It_is_unpleasant_to_learn_Catalan ~ 1 + political_orientation + gender + age + political_orientation:gender:age, data = qp_data)

summary(mod_null_It_is_unpleasant_to_learn_Catalan)
summary(mod_1_It_is_unpleasant_to_learn_Catalan)
summary(mod_2_It_is_unpleasant_to_learn_Catalan)
summary(mod_3_It_is_unpleasant_to_learn_Catalan)
summary(mod_int_It_is_unpleasant_to_learn_Catalan)

anova(mod_null_It_is_unpleasant_to_learn_Catalan, mod_1_It_is_unpleasant_to_learn_Catalan, mod_2_It_is_unpleasant_to_learn_Catalan, mod_3_It_is_unpleasant_to_learn_Catalan, mod_int_It_is_unpleasant_to_learn_Catalan)

ggplot(
  data = qp_data, 
  aes(
    x = political_orientation,
    y = It_is_unpleasant_to_learn_Catalan)) + 
  geom_point() + 
  geom_boxplot()


ggplot(
  data = qp_data, 
  aes(
    x = political_orientation,
    y = It_is_unpleasant_to_learn_Catalan, 
    fill = political_orientation)) + 
  geom_point(size = 1) +  # Set the size of the points on the plot
  stat_summary(fun.data = mean_se, geom = "pointrange", pch = 23, size = 1) +
  labs(x = "Political orientation", y = "It is unpleasant to learn Catalan", fill = "Political Orientation") +
  scale_fill_manual(values = c("indianred2", "indianred2", "indianred2", "cornflowerblue", "cornflowerblue", "cornflowerblue")) +
  theme(
    legend.key.size = unit(1, "lines"),  # Set the size of the legend key
    legend.key.width = unit(1.5, "lines"),  # Set the width of the legend key
    legend.spacing.x = unit(0.5, "lines")  # Adjust spacing between legend items
  ) +
  guides(fill = guide_legend(override.aes = list(size = 0.5)))  # Set the size of points in the legend



```


```{r}
mod_null_Sometimes_I_feel_compelled_to_use_Spanish <- lm(Sometimes_I_feel_compelled_to_use_Spanish ~ 1, data = qp_data)

mod_1_Sometimes_I_feel_compelled_to_use_Spanish <- lm(Sometimes_I_feel_compelled_to_use_Spanish ~ 1 + political_orientation, data = qp_data)

mod_2_Sometimes_I_feel_compelled_to_use_Spanish <- lm(Sometimes_I_feel_compelled_to_use_Spanish ~ 1 + political_orientation + gender, data = qp_data)

mod_3_Sometimes_I_feel_compelled_to_use_Spanish <- lm(Sometimes_I_feel_compelled_to_use_Spanish ~ 1 + political_orientation + gender + age, data = qp_data)

mod_int_Sometimes_I_feel_compelled_to_use_Spanish <- lm(Sometimes_I_feel_compelled_to_use_Spanish ~ 1 + political_orientation + gender + age + political_orientation:gender:age, data = qp_data)

summary(mod_null_Sometimes_I_feel_compelled_to_use_Spanish)
summary(mod_1_Sometimes_I_feel_compelled_to_use_Spanish)
summary(mod_2_Sometimes_I_feel_compelled_to_use_Spanish)
summary(mod_3_Sometimes_I_feel_compelled_to_use_Spanish)
summary(mod_int_Sometimes_I_feel_compelled_to_use_Spanish)

anova(mod_null_Sometimes_I_feel_compelled_to_use_Spanish, mod_1_Sometimes_I_feel_compelled_to_use_Spanish, mod_2_Sometimes_I_feel_compelled_to_use_Spanish, mod_3_Sometimes_I_feel_compelled_to_use_Spanish, mod_int_Sometimes_I_feel_compelled_to_use_Spanish)

ggplot(
  data = qp_data, 
  aes(
    x = political_orientation,
    y = Sometimes_I_feel_compelled_to_use_Spanish)) + 
  geom_point() + 
  geom_boxplot()

```

```{r, It is unpleasant to learn Spanish}

mod_null_It_is_unpleasant_to_learn_Spanish <- lm(It_is_unpleasant_to_learn_Spanish ~ 1, data = qp_data)

mod_1_It_is_unpleasant_to_learn_Spanish <- lm(It_is_unpleasant_to_learn_Spanish ~ 1 + political_orientation, data = qp_data)

mod_2_It_is_unpleasant_to_learn_Spanish <- lm(It_is_unpleasant_to_learn_Spanish ~ 1 + political_orientation + gender, data = qp_data)

mod_3_It_is_unpleasant_to_learn_Spanish <- lm(It_is_unpleasant_to_learn_Spanish ~ 1 + political_orientation + gender + age, data = qp_data)

mod_int_It_is_unpleasant_to_learn_Spanish <- lm(It_is_unpleasant_to_learn_Spanish ~ 1 + political_orientation + gender + age + political_orientation:gender:age, data = qp_data)

summary(mod_null_It_is_unpleasant_to_learn_Spanish)
summary(mod_1_It_is_unpleasant_to_learn_Spanish)
summary(mod_2_It_is_unpleasant_to_learn_Spanish)
summary(mod_3_It_is_unpleasant_to_learn_Spanish)
summary(mod_int_It_is_unpleasant_to_learn_Spanish)

anova(mod_null_It_is_unpleasant_to_learn_Spanish, mod_1_It_is_unpleasant_to_learn_Spanish, mod_2_It_is_unpleasant_to_learn_Spanish, mod_3_It_is_unpleasant_to_learn_Spanish, mod_int_It_is_unpleasant_to_learn_Spanish)

ggplot(
  data = qp_data, 
  aes(
    x = political_orientation,
    y = It_is_unpleasant_to_learn_Spanish)) + 
  geom_point() + 
  geom_boxplot()
```


```{r, It is boring to learn Catalan}

mod_null_It_is_boring_to_learn_Catalan <- lm(It_is_boring_to_learn_Catalan ~ 1, data = qp_data)

mod_1_It_is_boring_to_learn_Catalan <- lm(It_is_boring_to_learn_Catalan ~ 1 + political_orientation, data = qp_data)

mod_2_It_is_boring_to_learn_Catalan <- lm(It_is_boring_to_learn_Catalan ~ 1 + political_orientation + gender, data = qp_data)

mod_3_It_is_boring_to_learn_Catalan <- lm(It_is_boring_to_learn_Catalan ~ 1 + political_orientation + gender + age, data = qp_data)

mod_int_It_is_boring_to_learn_Catalan <- lm(It_is_boring_to_learn_Catalan ~ 1 + political_orientation + gender + age + political_orientation:gender:age, data = qp_data)

summary(mod_null_It_is_boring_to_learn_Catalan)
summary(mod_1_It_is_boring_to_learn_Catalan)
summary(mod_2_It_is_boring_to_learn_Catalan)
summary(mod_3_It_is_boring_to_learn_Catalan)
summary(mod_int_It_is_boring_to_learn_Catalan)

anova(mod_null_It_is_boring_to_learn_Catalan, mod_1_It_is_boring_to_learn_Catalan, mod_2_It_is_boring_to_learn_Catalan, mod_3_It_is_boring_to_learn_Catalan, mod_int_It_is_boring_to_learn_Catalan)

ggplot(
  data = qp_data, 
  aes(
    x = political_orientation,
    y = It_is_boring_to_learn_Catalan)) + 
  geom_point() + 
  geom_boxplot()


ggplot(
  data = qp_data, 
  aes(
    x = political_orientation,
    y = It_is_boring_to_learn_Catalan, 
    fill = political_orientation)) + 
  geom_point(size = 1) +  # Set the size of the points on the plot
  stat_summary(fun.data = mean_se, geom = "pointrange", pch = 23, size = 1) +
  labs(x = "Political orientation", y = "It is boring to learn Catalan", fill = "Political Orientation") +
  scale_fill_manual(values = c("indianred2", "indianred2", "indianred2", "cornflowerblue", "cornflowerblue", "cornflowerblue")) +
  theme(
    legend.key.size = unit(1, "lines"),  # Set the size of the legend key
    legend.key.width = unit(1.5, "lines"),  # Set the width of the legend key
    legend.spacing.x = unit(0.5, "lines")  # Adjust spacing between legend items
  ) +
  guides(fill = guide_legend(override.aes = list(size = 0.5)))  # Set the size of points in the legend

```

```{r, Learning Spanish is boring}

mod_null_Learning_Spanish_is_boring <- lm(Learning_Spanish_is_boring ~ 1, data = qp_data)

mod_1_Learning_Spanish_is_boring <- lm(Learning_Spanish_is_boring ~ 1 + political_orientation, data = qp_data)

mod_2_Learning_Spanish_is_boring <- lm(Learning_Spanish_is_boring ~ 1 + political_orientation + gender, data = qp_data)

mod_3_Learning_Spanish_is_boring <- lm(Learning_Spanish_is_boring ~ 1 + political_orientation + gender + age, data = qp_data)

mod_int_Learning_Spanish_is_boring <- lm(Learning_Spanish_is_boring ~ 1 + political_orientation + gender + age + political_orientation:gender:age, data = qp_data)

summary(mod_null_Learning_Spanish_is_boring)
summary(mod_1_Learning_Spanish_is_boring)
summary(mod_2_Learning_Spanish_is_boring)
summary(mod_3_Learning_Spanish_is_boring)
summary(mod_int_Learning_Spanish_is_boring)

anova(mod_null_Learning_Spanish_is_boring, mod_1_Learning_Spanish_is_boring, mod_2_Learning_Spanish_is_boring, mod_3_Learning_Spanish_is_boring, mod_int_Learning_Spanish_is_boring)

ggplot(
  data = qp_data, 
  aes(
    x = political_orientation,
    y = Learning_Spanish_is_boring)) + 
  geom_point() + 
  geom_boxplot()

```

```{r, People should put more effort into using Catalan}

mod_null_People_should_put_more_effort_into_using_Catalan <- lm(People_should_put_more_effort_into_using_Catalan ~ 1, data = qp_data)

mod_1_People_should_put_more_effort_into_using_Catalan <- lm(People_should_put_more_effort_into_using_Catalan ~ 1 + political_orientation, data = qp_data)

mod_2_People_should_put_more_effort_into_using_Catalan <- lm(People_should_put_more_effort_into_using_Catalan ~ 1 + political_orientation + gender, data = qp_data)

mod_3_People_should_put_more_effort_into_using_Catalan <- lm(People_should_put_more_effort_into_using_Catalan ~ 1 + political_orientation + gender + age, data = qp_data)

mod_int_People_should_put_more_effort_into_using_Catalan <- lm(People_should_put_more_effort_into_using_Catalan ~ 1 + political_orientation + gender + age + political_orientation:gender:age, data = qp_data)

summary(mod_null_People_should_put_more_effort_into_using_Catalan)
summary(mod_1_People_should_put_more_effort_into_using_Catalan)
summary(mod_2_People_should_put_more_effort_into_using_Catalan)
summary(mod_3_People_should_put_more_effort_into_using_Catalan)
summary(mod_int_People_should_put_more_effort_into_using_Catalan)

anova(mod_null_People_should_put_more_effort_into_using_Catalan, mod_1_People_should_put_more_effort_into_using_Catalan, mod_2_People_should_put_more_effort_into_using_Catalan, mod_3_People_should_put_more_effort_into_using_Catalan, mod_int_People_should_put_more_effort_into_using_Catalan)

ggplot(
  data = qp_data, 
  aes(
    x = political_orientation,
    y = People_should_put_more_effort_into_using_Catalan, fill = political_orientation)) + 
  geom_point() + 
  geom_boxplot() +
  labs(x = "Political orientation", y = "People should put more effort into using Catalan", fill = "Political Orientation") +
    scale_fill_manual(values = c("indianred2", "indianred2", "indianred2", "cornflowerblue", "cornflowerblue", "cornflowerblue"))


ggplot(
  data = qp_data, 
  aes(
    x = political_orientation,
    y = People_should_put_more_effort_into_using_Catalan, 
    fill = political_orientation)) + 
  geom_point(size = 1) +  # Set the size of the points on the plot
  stat_summary(fun.data = mean_se, geom = "pointrange", pch = 23, size = 1) +
  labs(x = "Political orientation", y = "People should put more effort into using Catalan", fill = "Political Orientation") +
  scale_fill_manual(values = c("indianred2", "indianred2", "indianred2", "cornflowerblue", "cornflowerblue", "cornflowerblue")) +
  theme(
    legend.key.size = unit(1, "lines"),  # Set the size of the legend key
    legend.key.width = unit(1.5, "lines"),  # Set the width of the legend key
    legend.spacing.x = unit(0.5, "lines")  # Adjust spacing between legend items
  ) +
  guides(fill = guide_legend(override.aes = list(size = 0.5)))  # Set the size of points in the legend

```

```{r, people should put more effort into using Spanish}

mod_null_People_should_put_more_effort_into_using_Spanish <- lm(People_should_put_more_effort_into_using_Spanish ~ 1, data = qp_data)

mod_1_People_should_put_more_effort_into_using_Spanish <- lm(People_should_put_more_effort_into_using_Spanish ~ 1 + political_orientation, data = qp_data)

mod_2_People_should_put_more_effort_into_using_Spanish <- lm(People_should_put_more_effort_into_using_Spanish ~ 1 + political_orientation + gender, data = qp_data)

mod_3_People_should_put_more_effort_into_using_Spanish <- lm(People_should_put_more_effort_into_using_Spanish ~ 1 + political_orientation + gender + age, data = qp_data)

mod_int_People_should_put_more_effort_into_using_Spanish <- lm(People_should_put_more_effort_into_using_Spanish ~ 1 + political_orientation + gender + age + political_orientation:gender:age, data = qp_data)

summary(mod_null_People_should_put_more_effort_into_using_Spanish)
summary(mod_1_People_should_put_more_effort_into_using_Spanish)
summary(mod_2_People_should_put_more_effort_into_using_Spanish)
summary(mod_3_People_should_put_more_effort_into_using_Spanish)
summary(mod_int_People_should_put_more_effort_into_using_Spanish)

anova(mod_null_People_should_put_more_effort_into_using_Spanish, mod_1_People_should_put_more_effort_into_using_Spanish, mod_2_People_should_put_more_effort_into_using_Spanish, mod_3_People_should_put_more_effort_into_using_Spanish, mod_int_People_should_put_more_effort_into_using_Spanish)

ggplot(
  data = qp_data, 
  aes(
    x = political_orientation,
    y = People_should_put_more_effort_into_using_Spanish, fill = political_orientation)) + 
  geom_point() + 
  geom_boxplot() +
  labs(x = "Political orientation", y = "People should put more effort into using Spanish", fill = "Political Orientation") +
    scale_fill_manual(values = c("indianred2", "indianred2", "indianred2", "cornflowerblue", "cornflowerblue", "cornflowerblue"))

ggplot(
  data = qp_data, 
  aes(
    x = political_orientation,
    y = People_should_put_more_effort_into_using_Spanish, 
    fill = political_orientation)) + 
  geom_point(size = 1) +  # Set the size of the points on the plot
  stat_summary(fun.data = mean_se, geom = "pointrange", pch = 23, size = 1) +
  labs(x = "Political orientation", y = "People should put more effort into using Spanish", fill = "Political Orientation") +
  scale_fill_manual(values = c("indianred2", "indianred2", "indianred2", "cornflowerblue", "cornflowerblue", "cornflowerblue")) +
  theme(
    legend.key.size = unit(1, "lines"),  # Set the size of the legend key
    legend.key.width = unit(1.5, "lines"),  # Set the width of the legend key
    legend.spacing.x = unit(0.5, "lines")  # Adjust spacing between legend items
  ) +
  guides(fill = guide_legend(override.aes = list(size = 0.5)))  # Set the size of points in the legend

```

```{r}
# Sample data
df <- data.frame(original_column = c(1, 2, 3, 4, 5))

# Rename the column
names(qp_data)[names(qp_data) == "I_live_in_the_Balearic_Islands_and_I have_to_know_study_and_use_Catalan"] <- "I_live_in_the_Balearic_Islands_and_I_have_to_know_study_and_use_Catalan"

# Display the modified data frame
print(df)
```




```{r, I live in the Balearic Islands and I have to know study and use Catalan}

mod_null_I_live_in_the_Balearic_Islands_and_I_have_to_know_study_and_use_Catalan <- lm(I_live_in_the_Balearic_Islands_and_I_have_to_know_study_and_use_Catalan ~ 1, data = qp_data)

mod_1_I_live_in_the_Balearic_Islands_and_I_have_to_know_study_and_use_Catalan <- lm(I_live_in_the_Balearic_Islands_and_I_have_to_know_study_and_use_Catalan ~ 1 + political_orientation, data = qp_data)

mod_2_I_live_in_the_Balearic_Islands_and_I_have_to_know_study_and_use_Catalan <- lm(I_live_in_the_Balearic_Islands_and_I_have_to_know_study_and_use_Catalan ~ 1 + political_orientation + gender, data = qp_data)

mod_3_I_live_in_the_Balearic_Islands_and_I_have_to_know_study_and_use_Catalan <- lm(I_live_in_the_Balearic_Islands_and_I_have_to_know_study_and_use_Catalan ~ 1 + political_orientation + gender + age, data = qp_data)

mod_int_I_live_in_the_Balearic_Islands_and_I_have_to_know_study_and_use_Catalan <- lm(I_live_in_the_Balearic_Islands_and_I_have_to_know_study_and_use_Catalan ~ 1 + political_orientation + gender + age + political_orientation:gender:age, data = qp_data)

summary(mod_null_I_live_in_the_Balearic_Islands_and_I_have_to_know_study_and_use_Catalan)
summary(mod_1_I_live_in_the_Balearic_Islands_and_I_have_to_know_study_and_use_Catalan)
summary(mod_2_I_live_in_the_Balearic_Islands_and_I_have_to_know_study_and_use_Catalan)
summary(mod_3_I_live_in_the_Balearic_Islands_and_I_have_to_know_study_and_use_Catalan)
summary(mod_int_I_live_in_the_Balearic_Islands_and_I_have_to_know_study_and_use_Catalan)

anova(mod_null_I_live_in_the_Balearic_Islands_and_I_have_to_know_study_and_use_Catalan, mod_1_I_live_in_the_Balearic_Islands_and_I_have_to_know_study_and_use_Catalan, mod_2_I_live_in_the_Balearic_Islands_and_I_have_to_know_study_and_use_Catalan, mod_3_I_live_in_the_Balearic_Islands_and_I_have_to_know_study_and_use_Catalan, mod_int_I_live_in_the_Balearic_Islands_and_I_have_to_know_study_and_use_Catalan)

ggplot(
  data = qp_data, 
  aes(
    x = political_orientation,
    y = I_live_in_the_Balearic_Islands_and_I_have_to_know_study_and_use_Catalan, fill = political_orientation)) + 
  geom_point() + 
  geom_boxplot() +
  labs(x = "Political orientation", y = "I live in the Balearic Islands and I should know, study, and use Catalan", fill = "Political Orientation") +
    scale_fill_manual(values = c("indianred2", "indianred2", "indianred2", "cornflowerblue", "cornflowerblue", "cornflowerblue"))


ggplot(
  data = qp_data, 
  aes(
    x = political_orientation,
    y = I_live_in_the_Balearic_Islands_and_I_have_to_know_study_and_use_Catalan, 
    fill = political_orientation)) + 
  geom_point(size = 1) +  # Set the size of the points on the plot
  stat_summary(fun.data = mean_se, geom = "pointrange", pch = 23, size = 1) +
  labs(x = "Political orientation", y = "I need to know, study, and use Catalan", fill = "Political Orientation") +
  scale_fill_manual(values = c("indianred2", "indianred2", "indianred2", "cornflowerblue", "cornflowerblue", "cornflowerblue")) +
  theme(
    legend.key.size = unit(1, "lines"),  # Set the size of the legend key
    legend.key.width = unit(1.5, "lines"),  # Set the width of the legend key
    legend.spacing.x = unit(0.5, "lines")  # Adjust spacing between legend items
  ) +
  guides(fill = guide_legend(override.aes = list(size = 0.5)))  # Set the size of points in the legend

```

```{r, I live in the Balearic Islands and I have to know study and use Spanish}

mod_null_I_live_in_the_Balearic_Islands_and_I_have_to_know_study_and_use_Spanish <- lm(I_live_in_the_Balearic_Islands_and_I_have_to_know_study_and_use_Spanish ~ 1, data = qp_data)

mod_1_I_live_in_the_Balearic_Islands_and_I_have_to_know_study_and_use_Spanish <- lm(I_live_in_the_Balearic_Islands_and_I_have_to_know_study_and_use_Spanish ~ 1 + political_orientation, data = qp_data)

mod_2_I_live_in_the_Balearic_Islands_and_I_have_to_know_study_and_use_Spanish <- lm(I_live_in_the_Balearic_Islands_and_I_have_to_know_study_and_use_Spanish ~ 1 + political_orientation + gender, data = qp_data)

mod_3_I_live_in_the_Balearic_Islands_and_I_have_to_know_study_and_use_Spanish <- lm(I_live_in_the_Balearic_Islands_and_I_have_to_know_study_and_use_Spanish ~ 1 + political_orientation + gender + age, data = qp_data)

mod_int_I_live_in_the_Balearic_Islands_and_I_have_to_know_study_and_use_Spanish <- lm(I_live_in_the_Balearic_Islands_and_I_have_to_know_study_and_use_Spanish ~ 1 + political_orientation + gender + age + political_orientation:gender:age, data = qp_data)

summary(mod_null_I_live_in_the_Balearic_Islands_and_I_have_to_know_study_and_use_Spanish)
summary(mod_1_I_live_in_the_Balearic_Islands_and_I_have_to_know_study_and_use_Spanish)
summary(mod_2_I_live_in_the_Balearic_Islands_and_I_have_to_know_study_and_use_Spanish)
summary(mod_3_I_live_in_the_Balearic_Islands_and_I_have_to_know_study_and_use_Spanish)
summary(mod_int_I_live_in_the_Balearic_Islands_and_I_have_to_know_study_and_use_Spanish)

anova(mod_null_I_live_in_the_Balearic_Islands_and_I_have_to_know_study_and_use_Spanish, mod_1_I_live_in_the_Balearic_Islands_and_I_have_to_know_study_and_use_Spanish, mod_2_I_live_in_the_Balearic_Islands_and_I_have_to_know_study_and_use_Spanish, mod_3_I_live_in_the_Balearic_Islands_and_I_have_to_know_study_and_use_Spanish, mod_int_I_live_in_the_Balearic_Islands_and_I_have_to_know_study_and_use_Spanish)

ggplot(
  data = qp_data, 
  aes(
    x = political_orientation,
    y = I_live_in_the_Balearic_Islands_and_I_have_to_know_study_and_use_Spanish)) + 
  geom_point() + 
  geom_boxplot()
```

```{r, Catalan is a language that sounds bad}

mod_null_Catalan_is_a_language_that_sounds_bad <- lm(Catalan_is_a_language_that_sounds_bad ~ 1, data = qp_data)

mod_1_Catalan_is_a_language_that_sounds_bad <- lm(Catalan_is_a_language_that_sounds_bad ~ 1 + political_orientation, data = qp_data)

mod_2_Catalan_is_a_language_that_sounds_bad <- lm(Catalan_is_a_language_that_sounds_bad ~ 1 + political_orientation + gender, data = qp_data)

mod_3_Catalan_is_a_language_that_sounds_bad <- lm(Catalan_is_a_language_that_sounds_bad ~ 1 + political_orientation + gender + age, data = qp_data)

mod_int_Catalan_is_a_language_that_sounds_bad <- lm(Catalan_is_a_language_that_sounds_bad ~ 1 + political_orientation + gender + age + political_orientation:gender:age, data = qp_data)

summary(mod_null_Catalan_is_a_language_that_sounds_bad)
summary(mod_1_Catalan_is_a_language_that_sounds_bad)
summary(mod_2_Catalan_is_a_language_that_sounds_bad)
summary(mod_3_Catalan_is_a_language_that_sounds_bad)
summary(mod_int_Catalan_is_a_language_that_sounds_bad)

anova(mod_null_Catalan_is_a_language_that_sounds_bad, mod_1_Catalan_is_a_language_that_sounds_bad, mod_2_Catalan_is_a_language_that_sounds_bad, mod_3_Catalan_is_a_language_that_sounds_bad, mod_int_Catalan_is_a_language_that_sounds_bad)

ggplot(
  data = qp_data, 
  aes(
    x = political_orientation,
    y = Catalan_is_a_language_that_sounds_bad)) + 
  geom_point() + 
  geom_boxplot()

```


```{r, Spanish is a language that sounds bad}

mod_null_Spanish_is_a_language_that_sounds_bad <- lm(Spanish_is_a_language_that_sounds_bad ~ 1, data = qp_data)

mod_1_Spanish_is_a_language_that_sounds_bad <- lm(Spanish_is_a_language_that_sounds_bad ~ 1 + political_orientation, data = qp_data)

mod_2_Spanish_is_a_language_that_sounds_bad <- lm(Spanish_is_a_language_that_sounds_bad ~ 1 + political_orientation + gender, data = qp_data)

mod_3_Spanish_is_a_language_that_sounds_bad <- lm(Spanish_is_a_language_that_sounds_bad ~ 1 + political_orientation + gender + age, data = qp_data)

mod_int_Spanish_is_a_language_that_sounds_bad <- lm(Spanish_is_a_language_that_sounds_bad ~ 1 + political_orientation + gender + age + political_orientation:gender:age, data = qp_data)

summary(mod_null_Spanish_is_a_language_that_sounds_bad)
summary(mod_1_Spanish_is_a_language_that_sounds_bad)
summary(mod_2_Spanish_is_a_language_that_sounds_bad)
summary(mod_3_Spanish_is_a_language_that_sounds_bad)
summary(mod_int_Spanish_is_a_language_that_sounds_bad)

anova(mod_null_Spanish_is_a_language_that_sounds_bad, mod_1_Spanish_is_a_language_that_sounds_bad, mod_2_Spanish_is_a_language_that_sounds_bad, mod_3_Spanish_is_a_language_that_sounds_bad, mod_int_Spanish_is_a_language_that_sounds_bad)

ggplot(
  data = qp_data, 
  aes(
    x = political_orientation,
    y = Spanish_is_a_language_that_sounds_bad)) + 
  geom_point() + 
  geom_boxplot()


```

```{r, It bothers me when a stranger chats with me in Catalan}

mod_null_It_bothers_me_when_a_stranger_chats_with_me_in_Catalan <- lm(It_bothers_me_when_a_stranger_chats_with_me_in_Catalan ~ 1, data = qp_data)

mod_1_It_bothers_me_when_a_stranger_chats_with_me_in_Catalan <- lm(It_bothers_me_when_a_stranger_chats_with_me_in_Catalan ~ 1 + political_orientation, data = qp_data)

mod_2_It_bothers_me_when_a_stranger_chats_with_me_in_Catalan <- lm(It_bothers_me_when_a_stranger_chats_with_me_in_Catalan ~ 1 + political_orientation + gender, data = qp_data)

mod_3_It_bothers_me_when_a_stranger_chats_with_me_in_Catalan <- lm(It_bothers_me_when_a_stranger_chats_with_me_in_Catalan ~ 1 + political_orientation + gender + age, data = qp_data)

mod_int_It_bothers_me_when_a_stranger_chats_with_me_in_Catalan <- lm(It_bothers_me_when_a_stranger_chats_with_me_in_Catalan ~ 1 + political_orientation + gender + age + political_orientation:gender:age, data = qp_data)

summary(mod_null_It_bothers_me_when_a_stranger_chats_with_me_in_Catalan)
summary(mod_1_It_bothers_me_when_a_stranger_chats_with_me_in_Catalan)
summary(mod_2_It_bothers_me_when_a_stranger_chats_with_me_in_Catalan)
summary(mod_3_It_bothers_me_when_a_stranger_chats_with_me_in_Catalan)
summary(mod_int_It_bothers_me_when_a_stranger_chats_with_me_in_Catalan)

anova(mod_null_It_bothers_me_when_a_stranger_chats_with_me_in_Catalan, mod_1_It_bothers_me_when_a_stranger_chats_with_me_in_Catalan, mod_2_It_bothers_me_when_a_stranger_chats_with_me_in_Catalan, mod_3_It_bothers_me_when_a_stranger_chats_with_me_in_Catalan, mod_int_It_bothers_me_when_a_stranger_chats_with_me_in_Catalan)

ggplot(
  data = qp_data, 
  aes(
    x = political_orientation,
    y = It_bothers_me_when_a_stranger_chats_with_me_in_Catalan)) + 
  geom_point() + 
  geom_boxplot()


```

```{r}
mod_null_It_bothers_me_when_a_stranger_chats_with_me_in_Spanish <- lm(It_bothers_me_when_a_stranger_chats_with_me_in_Spanish ~ 1, data = qp_data)

mod_1_It_bothers_me_when_a_stranger_chats_with_me_in_Spanish <- lm(It_bothers_me_when_a_stranger_chats_with_me_in_Spanish ~ 1 + political_orientation, data = qp_data)

mod_2_It_bothers_me_when_a_stranger_chats_with_me_in_Spanish <- lm(It_bothers_me_when_a_stranger_chats_with_me_in_Spanish ~ 1 + political_orientation + gender, data = qp_data)

mod_3_It_bothers_me_when_a_stranger_chats_with_me_in_Spanish <- lm(It_bothers_me_when_a_stranger_chats_with_me_in_Spanish ~ 1 + political_orientation + gender + age, data = qp_data)

mod_int_It_bothers_me_when_a_stranger_chats_with_me_in_Spanish <- lm(It_bothers_me_when_a_stranger_chats_with_me_in_Spanish ~ 1 + political_orientation + gender + age + political_orientation:gender:age, data = qp_data)

summary(mod_null_It_bothers_me_when_a_stranger_chats_with_me_in_Spanish)
summary(mod_1_It_bothers_me_when_a_stranger_chats_with_me_in_Spanish)
summary(mod_2_It_bothers_me_when_a_stranger_chats_with_me_in_Spanish)
summary(mod_3_It_bothers_me_when_a_stranger_chats_with_me_in_Spanish)
summary(mod_int_It_bothers_me_when_a_stranger_chats_with_me_in_Spanish)

anova(mod_null_It_bothers_me_when_a_stranger_chats_with_me_in_Spanish, mod_1_It_bothers_me_when_a_stranger_chats_with_me_in_Spanish, mod_2_It_bothers_me_when_a_stranger_chats_with_me_in_Spanish, mod_3_It_bothers_me_when_a_stranger_chats_with_me_in_Spanish, mod_int_It_bothers_me_when_a_stranger_chats_with_me_in_Spanish)

ggplot(
  data = qp_data, 
  aes(
    x = political_orientation,
    y = It_bothers_me_when_a_stranger_chats_with_me_in_Spanish)) + 
  geom_point() + 
  geom_boxplot()

ggplot(
  data = qp_data, 
  aes(
    x = age,
    y = It_bothers_me_when_a_stranger_chats_with_me_in_Spanish)) + 
  geom_point() + 
  geom_boxplot()

```

```{r}
mod_null_It_is_not_good_manners_to_answer_in_Catalan_to_someone_who_speaks_to_you_in_Spanish <- lm(It_is_not_good_manners_to_answer_in_Catalan_to_someone_who_speaks_to_you_in_Spanish ~ 1, data = qp_data)

mod_1_It_is_not_good_manners_to_answer_in_Catalan_to_someone_who_speaks_to_you_in_Spanish <- lm(It_is_not_good_manners_to_answer_in_Catalan_to_someone_who_speaks_to_you_in_Spanish ~ 1 + political_orientation, data = qp_data)

mod_2_It_is_not_good_manners_to_answer_in_Catalan_to_someone_who_speaks_to_you_in_Spanish <- lm(It_is_not_good_manners_to_answer_in_Catalan_to_someone_who_speaks_to_you_in_Spanish ~ 1 + political_orientation + gender, data = qp_data)

mod_3_It_is_not_good_manners_to_answer_in_Catalan_to_someone_who_speaks_to_you_in_Spanish <- lm(It_is_not_good_manners_to_answer_in_Catalan_to_someone_who_speaks_to_you_in_Spanish ~ 1 + political_orientation + gender + age, data = qp_data)

mod_int_It_is_not_good_manners_to_answer_in_Catalan_to_someone_who_speaks_to_you_in_Spanish <- lm(It_is_not_good_manners_to_answer_in_Catalan_to_someone_who_speaks_to_you_in_Spanish ~ 1 + political_orientation + gender + age + political_orientation:gender:age, data = qp_data)

summary(mod_null_It_is_not_good_manners_to_answer_in_Catalan_to_someone_who_speaks_to_you_in_Spanish)
summary(mod_1_It_is_not_good_manners_to_answer_in_Catalan_to_someone_who_speaks_to_you_in_Spanish)
summary(mod_2_It_is_not_good_manners_to_answer_in_Catalan_to_someone_who_speaks_to_you_in_Spanish)
summary(mod_3_It_is_not_good_manners_to_answer_in_Catalan_to_someone_who_speaks_to_you_in_Spanish)
summary(mod_int_It_is_not_good_manners_to_answer_in_Catalan_to_someone_who_speaks_to_you_in_Spanish)

anova(mod_null_It_is_not_good_manners_to_answer_in_Catalan_to_someone_who_speaks_to_you_in_Spanish, mod_1_It_is_not_good_manners_to_answer_in_Catalan_to_someone_who_speaks_to_you_in_Spanish, mod_2_It_is_not_good_manners_to_answer_in_Catalan_to_someone_who_speaks_to_you_in_Spanish, mod_3_It_is_not_good_manners_to_answer_in_Catalan_to_someone_who_speaks_to_you_in_Spanish, mod_int_It_is_not_good_manners_to_answer_in_Catalan_to_someone_who_speaks_to_you_in_Spanish)

ggplot(
  data = qp_data, 
  aes(
    x = political_orientation,
    y = It_is_not_good_manners_to_answer_in_Catalan_to_someone_who_speaks_to_you_in_Spanish, fill = political_orientation)) + 
  geom_point() + 
  geom_boxplot() +
  labs(x = "Political orientation", y = "It is not good manners to answer in Catalan to someone who speaks to you in Spanish", fill = "Political Orientation") +
    scale_fill_manual(values = c("indianred2", "indianred2", "indianred2", "cornflowerblue", "cornflowerblue", "cornflowerblue"))


ggplot(
  data = qp_data, 
  aes(
    x = political_orientation,
    y = It_is_not_good_manners_to_answer_in_Catalan_to_someone_who_speaks_to_you_in_Spanish, 
    fill = political_orientation)) + 
  geom_point(size = 1) +  # Set the size of the points on the plot
  stat_summary(fun.data = mean_se, geom = "pointrange", pch = 23, size = 1) +
  labs(x = "Political orientation", y = "Not good manners to respond in Catalan", fill = "Political Orientation") +
  scale_fill_manual(values = c("indianred2", "indianred2", "indianred2", "cornflowerblue", "cornflowerblue", "cornflowerblue")) +
  theme(
    legend.key.size = unit(1, "lines"),  # Set the size of the legend key
    legend.key.width = unit(1.5, "lines"),  # Set the width of the legend key
    legend.spacing.x = unit(0.5, "lines")  # Adjust spacing between legend items
  ) +
  guides(fill = guide_legend(override.aes = list(size = 0.5)))  # Set the size of points in the legend



```

```{r}
mod_null_It_is_not_good_manners_to_answer_in_Spanish_to_someone_who_speaks_Catalan <- lm(It_is_not_good_manners_to_answer_in_Spanish_to_someone_who_speaks_Catalan ~ 1, data = qp_data)

mod_1_It_is_not_good_manners_to_answer_in_Spanish_to_someone_who_speaks_Catalan <- lm(It_is_not_good_manners_to_answer_in_Spanish_to_someone_who_speaks_Catalan ~ 1 + political_orientation, data = qp_data)

mod_2_It_is_not_good_manners_to_answer_in_Spanish_to_someone_who_speaks_Catalan <- lm(It_is_not_good_manners_to_answer_in_Spanish_to_someone_who_speaks_Catalan ~ 1 + political_orientation + gender, data = qp_data)

mod_3_It_is_not_good_manners_to_answer_in_Spanish_to_someone_who_speaks_Catalan <- lm(It_is_not_good_manners_to_answer_in_Spanish_to_someone_who_speaks_Catalan ~ 1 + political_orientation + gender + age, data = qp_data)

mod_int_It_is_not_good_manners_to_answer_in_Spanish_to_someone_who_speaks_Catalan <- lm(It_is_not_good_manners_to_answer_in_Spanish_to_someone_who_speaks_Catalan ~ 1 + political_orientation + gender + age + political_orientation:gender:age, data = qp_data)

summary(mod_null_It_is_not_good_manners_to_answer_in_Spanish_to_someone_who_speaks_Catalan)
summary(mod_1_It_is_not_good_manners_to_answer_in_Spanish_to_someone_who_speaks_Catalan)
summary(mod_2_It_is_not_good_manners_to_answer_in_Spanish_to_someone_who_speaks_Catalan)
summary(mod_3_It_is_not_good_manners_to_answer_in_Spanish_to_someone_who_speaks_Catalan)
summary(mod_int_It_is_not_good_manners_to_answer_in_Spanish_to_someone_who_speaks_Catalan)

anova(mod_null_It_is_not_good_manners_to_answer_in_Spanish_to_someone_who_speaks_Catalan, mod_1_It_is_not_good_manners_to_answer_in_Spanish_to_someone_who_speaks_Catalan, mod_2_It_is_not_good_manners_to_answer_in_Spanish_to_someone_who_speaks_Catalan, mod_3_It_is_not_good_manners_to_answer_in_Spanish_to_someone_who_speaks_Catalan, mod_int_It_is_not_good_manners_to_answer_in_Spanish_to_someone_who_speaks_Catalan)

ggplot(
  data = qp_data, 
  aes(
    x = political_orientation,
    y = It_is_not_good_manners_to_answer_in_Spanish_to_someone_who_speaks_Catalan)) + 
  geom_point() + 
  geom_boxplot()
```

```{r}
mod_null_Catalan_is_as_important_as_English <- lm(Catalan_is_as_important_as_English ~ 1, data = qp_data)

mod_1_Catalan_is_as_important_as_English <- lm(Catalan_is_as_important_as_English ~ 1 + political_orientation, data = qp_data)

mod_2_Catalan_is_as_important_as_English <- lm(Catalan_is_as_important_as_English ~ 1 + political_orientation + gender, data = qp_data)

mod_3_Catalan_is_as_important_as_English <- lm(Catalan_is_as_important_as_English ~ 1 + political_orientation + gender + age, data = qp_data)

mod_int_Catalan_is_as_important_as_English <- lm(Catalan_is_as_important_as_English ~ 1 + political_orientation + gender + age + political_orientation:gender:age, data = qp_data)

summary(mod_null_Catalan_is_as_important_as_English)
summary(mod_1_Catalan_is_as_important_as_English)
summary(mod_2_Catalan_is_as_important_as_English)
summary(mod_3_Catalan_is_as_important_as_English)
summary(mod_int_Catalan_is_as_important_as_English)

anova(mod_null_Catalan_is_as_important_as_English, mod_1_Catalan_is_as_important_as_English, mod_2_Catalan_is_as_important_as_English, mod_3_Catalan_is_as_important_as_English, mod_int_Catalan_is_as_important_as_English)

ggplot(
  data = qp_data, 
  aes(
    x = political_orientation,
    y = Catalan_is_as_important_as_English, fill = political_orientation)) + 
  geom_point() + 
  geom_boxplot() +
  labs(x = "Political orientation", y = "Catalan is as important as English", fill = "Political Orientation") +
    scale_fill_manual(values = c("indianred2", "indianred2", "indianred2", "cornflowerblue", "cornflowerblue", "cornflowerblue"))

ggplot(
  data = qp_data, 
  aes(
    x = political_orientation,
    y = Catalan_is_as_important_as_English, 
    fill = political_orientation)) + 
  geom_point(size = 1) +  # Set the size of the points on the plot
  stat_summary(fun.data = mean_se, geom = "pointrange", pch = 23, size = 1) +
  labs(x = "Political orientation", y = "Catalan is as important as English", fill = "Political Orientation") +
  scale_fill_manual(values = c("indianred2", "indianred2", "indianred2", "cornflowerblue", "cornflowerblue", "cornflowerblue")) +
  theme(
    legend.key.size = unit(1, "lines"),  # Set the size of the legend key
    legend.key.width = unit(1.5, "lines"),  # Set the width of the legend key
    legend.spacing.x = unit(0.5, "lines")  # Adjust spacing between legend items
  ) +
  guides(fill = guide_legend(override.aes = list(size = 0.5)))  # Set the size of points in the legend


```

```{r}
mod_null_Spanish_is_as_important_as_English <- lm(Spanish_is_as_important_as_English ~ 1, data = qp_data)

mod_1_Spanish_is_as_important_as_English <- lm(Spanish_is_as_important_as_English ~ 1 + political_orientation, data = qp_data)

mod_2_Spanish_is_as_important_as_English <- lm(Spanish_is_as_important_as_English ~ 1 + political_orientation + gender, data = qp_data)

mod_3_Spanish_is_as_important_as_English <- lm(Spanish_is_as_important_as_English ~ 1 + political_orientation + gender + age, data = qp_data)

mod_int_Spanish_is_as_important_as_English <- lm(Spanish_is_as_important_as_English ~ 1 + political_orientation + gender + age + political_orientation:gender:age, data = qp_data)

summary(mod_null_Spanish_is_as_important_as_English)
summary(mod_1_Spanish_is_as_important_as_English)
summary(mod_2_Spanish_is_as_important_as_English)
summary(mod_3_Spanish_is_as_important_as_English)
summary(mod_int_Spanish_is_as_important_as_English)

anova(mod_null_Spanish_is_as_important_as_English, mod_1_Spanish_is_as_important_as_English, mod_2_Spanish_is_as_important_as_English, mod_3_Spanish_is_as_important_as_English, mod_int_Spanish_is_as_important_as_English)

ggplot(
  data = qp_data, 
  aes(
    x = political_orientation,
    y = Spanish_is_as_important_as_English, fill = political_orientation)) + 
  geom_point() + 
  geom_boxplot() +
  labs(x = "Political orientation", y = "Spanish is as important as English", fill = "Political Orientation") +
    scale_fill_manual(values = c("indianred2", "indianred2", "indianred2", "cornflowerblue", "cornflowerblue", "cornflowerblue"))


ggplot(
  data = qp_data, 
  aes(
    x = political_orientation,
    y = Spanish_is_as_important_as_English, 
    fill = political_orientation)) + 
  geom_point(size = 1) +  # Set the size of the points on the plot
  stat_summary(fun.data = mean_se, geom = "pointrange", pch = 23, size = 1) +
  labs(x = "Political orientation", y = "Spanish is as important as English", fill = "Political Orientation") +
  scale_fill_manual(values = c("indianred2", "indianred2", "indianred2", "cornflowerblue", "cornflowerblue", "cornflowerblue")) +
  theme(
    legend.key.size = unit(1, "lines"),  # Set the size of the legend key
    legend.key.width = unit(1.5, "lines"),  # Set the width of the legend key
    legend.spacing.x = unit(0.5, "lines")  # Adjust spacing between legend items
  ) +
  guides(fill = guide_legend(override.aes = list(size = 0.5)))  # Set the size of points in the legend



```

```{r, I f I have children I would like them to speak Catalan}

mod_null_If_I_have_children_I_would_like_them_to_speak_Catalan <- lm(If_I_have_children_I_would_like_them_to_speak_Catalan ~ 1, data = qp_data)

mod_1_If_I_have_children_I_would_like_them_to_speak_Catalan <- lm(If_I_have_children_I_would_like_them_to_speak_Catalan ~ 1 + political_orientation, data = qp_data)

mod_2_If_I_have_children_I_would_like_them_to_speak_Catalan <- lm(If_I_have_children_I_would_like_them_to_speak_Catalan ~ 1 + political_orientation + gender, data = qp_data)

mod_3_If_I_have_children_I_would_like_them_to_speak_Catalan <- lm(If_I_have_children_I_would_like_them_to_speak_Catalan ~ 1 + political_orientation + gender + age, data = qp_data)

mod_int_If_I_have_children_I_would_like_them_to_speak_Catalan <- lm(If_I_have_children_I_would_like_them_to_speak_Catalan ~ 1 + political_orientation + gender + age + political_orientation:gender:age, data = qp_data)

summary(mod_null_If_I_have_children_I_would_like_them_to_speak_Catalan)
summary(mod_1_If_I_have_children_I_would_like_them_to_speak_Catalan)
summary(mod_2_If_I_have_children_I_would_like_them_to_speak_Catalan)
summary(mod_3_If_I_have_children_I_would_like_them_to_speak_Catalan)
summary(mod_int_If_I_have_children_I_would_like_them_to_speak_Catalan)

anova(mod_null_If_I_have_children_I_would_like_them_to_speak_Catalan, mod_1_If_I_have_children_I_would_like_them_to_speak_Catalan, mod_2_If_I_have_children_I_would_like_them_to_speak_Catalan, mod_3_If_I_have_children_I_would_like_them_to_speak_Catalan, mod_int_If_I_have_children_I_would_like_them_to_speak_Catalan)

ggplot(
  data = qp_data, 
  aes(
    x = political_orientation,
    y = If_I_have_children_I_would_like_them_to_speak_Catalan, fill = political_orientation)) + 
  geom_point() + 
  geom_boxplot() +
  labs(x = "Political orientation", y = "If I had children I would like them to speak Catalan", fill = "Political Orientation") +
    scale_fill_manual(values = c("indianred2", "indianred2", "indianred2", "cornflowerblue", "cornflowerblue", "cornflowerblue"))


ggplot(
  data = qp_data, 
  aes(
    x = political_orientation,
    y = If_I_have_children_I_would_like_them_to_speak_Catalan, 
    fill = political_orientation)) + 
  geom_point(size = 1) +  # Set the size of the points on the plot
  stat_summary(fun.data = mean_se, geom = "pointrange", pch = 23, size = 1) +
  labs(x = "Political orientation", y = "If I had children I would like them to speak Catalan", fill = "Political Orientation") +
  scale_fill_manual(values = c("indianred2", "indianred2", "indianred2", "cornflowerblue", "cornflowerblue", "cornflowerblue")) +
  theme(
    legend.key.size = unit(1, "lines"),  # Set the size of the legend key
    legend.key.width = unit(1.5, "lines"),  # Set the width of the legend key
    legend.spacing.x = unit(0.5, "lines")  # Adjust spacing between legend items
  ) +
  guides(fill = guide_legend(override.aes = list(size = 0.5)))  # Set the size of points in the legend



```

```{r}
mod_null_If_I_have_children_I_would_like_them_to_speak_Spanish <- lm(If_I_have_children_I_would_like_them_to_speak_Spanish ~ 1, data = qp_data)

mod_1_If_I_have_children_I_would_like_them_to_speak_Spanish <- lm(If_I_have_children_I_would_like_them_to_speak_Spanish ~ 1 + political_orientation, data = qp_data)

mod_2_If_I_have_children_I_would_like_them_to_speak_Spanish <- lm(If_I_have_children_I_would_like_them_to_speak_Spanish ~ 1 + political_orientation + gender, data = qp_data)

mod_3_If_I_have_children_I_would_like_them_to_speak_Spanish <- lm(If_I_have_children_I_would_like_them_to_speak_Spanish ~ 1 + political_orientation + gender + age, data = qp_data)

mod_int_If_I_have_children_I_would_like_them_to_speak_Spanish <- lm(If_I_have_children_I_would_like_them_to_speak_Spanish ~ 1 + political_orientation + gender + age + political_orientation:gender:age, data = qp_data)

summary(mod_null_If_I_have_children_I_would_like_them_to_speak_Spanish)
summary(mod_1_If_I_have_children_I_would_like_them_to_speak_Spanish)
summary(mod_2_If_I_have_children_I_would_like_them_to_speak_Spanish)
summary(mod_3_If_I_have_children_I_would_like_them_to_speak_Spanish)
summary(mod_int_If_I_have_children_I_would_like_them_to_speak_Spanish)

anova(mod_null_If_I_have_children_I_would_like_them_to_speak_Spanish, mod_1_If_I_have_children_I_would_like_them_to_speak_Spanish, mod_2_If_I_have_children_I_would_like_them_to_speak_Spanish, mod_3_If_I_have_children_I_would_like_them_to_speak_Spanish, mod_int_If_I_have_children_I_would_like_them_to_speak_Spanish)

ggplot(
  data = qp_data, 
  aes(
    x = political_orientation,
    y = If_I_have_children_I_would_like_them_to_speak_Spanish)) + 
  geom_point() + 
  geom_boxplot()
```

```{r, Since_we_all_speak_Spanish_it_is_not_necessary_that_people_who_come_from_other_Autonomous_Communities_or_Spanish_speaking_countries_learn_Catalan}

mod_null_Since_we_all_speak_Spanish_it_is_not_necessary_that_people_who_come_from_other_Autonomous_Communities_or_Spanish_speaking_countries_learn_Catalan <- lm(Since_we_all_speak_Spanish_it_is_not_necessary_that_people_who_come_from_other_Autonomous_Communities_or_Spanish_speaking_countries_learn_Catalan ~ 1, data = qp_data)

mod_1_Since_we_all_speak_Spanish_it_is_not_necessary_that_people_who_come_from_other_Autonomous_Communities_or_Spanish_speaking_countries_learn_Catalan <- lm(Since_we_all_speak_Spanish_it_is_not_necessary_that_people_who_come_from_other_Autonomous_Communities_or_Spanish_speaking_countries_learn_Catalan ~ 1 + political_orientation, data = qp_data)

mod_2_Since_we_all_speak_Spanish_it_is_not_necessary_that_people_who_come_from_other_Autonomous_Communities_or_Spanish_speaking_countries_learn_Catalan <- lm(Since_we_all_speak_Spanish_it_is_not_necessary_that_people_who_come_from_other_Autonomous_Communities_or_Spanish_speaking_countries_learn_Catalan ~ 1 + political_orientation + gender, data = qp_data)

mod_3_Since_we_all_speak_Spanish_it_is_not_necessary_that_people_who_come_from_other_Autonomous_Communities_or_Spanish_speaking_countries_learn_Catalan <- lm(Since_we_all_speak_Spanish_it_is_not_necessary_that_people_who_come_from_other_Autonomous_Communities_or_Spanish_speaking_countries_learn_Catalan ~ 1 + political_orientation + gender + age, data = qp_data)

mod_int_Since_we_all_speak_Spanish_it_is_not_necessary_that_people_who_come_from_other_Autonomous_Communities_or_Spanish_speaking_countries_learn_Catalan <- lm(Since_we_all_speak_Spanish_it_is_not_necessary_that_people_who_come_from_other_Autonomous_Communities_or_Spanish_speaking_countries_learn_Catalan ~ 1 + political_orientation + gender + age + political_orientation:gender:age, data = qp_data)

summary(mod_null_Since_we_all_speak_Spanish_it_is_not_necessary_that_people_who_come_from_other_Autonomous_Communities_or_Spanish_speaking_countries_learn_Catalan)
summary(mod_1_Since_we_all_speak_Spanish_it_is_not_necessary_that_people_who_come_from_other_Autonomous_Communities_or_Spanish_speaking_countries_learn_Catalan)
summary(mod_2_Since_we_all_speak_Spanish_it_is_not_necessary_that_people_who_come_from_other_Autonomous_Communities_or_Spanish_speaking_countries_learn_Catalan)
summary(mod_3_Since_we_all_speak_Spanish_it_is_not_necessary_that_people_who_come_from_other_Autonomous_Communities_or_Spanish_speaking_countries_learn_Catalan)
summary(mod_int_Since_we_all_speak_Spanish_it_is_not_necessary_that_people_who_come_from_other_Autonomous_Communities_or_Spanish_speaking_countries_learn_Catalan)

anova(mod_null_Since_we_all_speak_Spanish_it_is_not_necessary_that_people_who_come_from_other_Autonomous_Communities_or_Spanish_speaking_countries_learn_Catalan, mod_1_Since_we_all_speak_Spanish_it_is_not_necessary_that_people_who_come_from_other_Autonomous_Communities_or_Spanish_speaking_countries_learn_Catalan, mod_2_Since_we_all_speak_Spanish_it_is_not_necessary_that_people_who_come_from_other_Autonomous_Communities_or_Spanish_speaking_countries_learn_Catalan, mod_3_Since_we_all_speak_Spanish_it_is_not_necessary_that_people_who_come_from_other_Autonomous_Communities_or_Spanish_speaking_countries_learn_Catalan, mod_int_Since_we_all_speak_Spanish_it_is_not_necessary_that_people_who_come_from_other_Autonomous_Communities_or_Spanish_speaking_countries_learn_Catalan)

ggplot(
  data = qp_data, 
  aes(
    x = political_orientation,
    y = Since_we_all_speak_Spanish_it_is_not_necessary_that_people_who_come_from_other_Autonomous_Communities_or_Spanish_speaking_countries_learn_Catalan, fill = political_orientation)) + 
  geom_point() + 
  geom_boxplot() +
  labs(x = "Political orientation", y = "No need to learn Catalan", fill = "Political Orientation") +
    scale_fill_manual(values = c("indianred2", "indianred2", "indianred2", "cornflowerblue", "cornflowerblue", "cornflowerblue"))


ggplot(
  data = qp_data, 
  aes(
    x = political_orientation,
    y = Since_we_all_speak_Spanish_it_is_not_necessary_that_people_who_come_from_other_Autonomous_Communities_or_Spanish_speaking_countries_learn_Catalan, 
    fill = political_orientation)) + 
  geom_point(size = 1) +  # Set the size of the points on the plot
  stat_summary(fun.data = mean_se, geom = "pointrange", pch = 23, size = 1) +
  labs(x = "Political orientation", y = "No need to learn Catalan", fill = "Political Orientation") +
  scale_fill_manual(values = c("indianred2", "indianred2", "indianred2", "cornflowerblue", "cornflowerblue", "cornflowerblue")) +
  theme(
    legend.key.size = unit(1, "lines"),  # Set the size of the legend key
    legend.key.width = unit(1.5, "lines"),  # Set the width of the legend key
    legend.spacing.x = unit(0.5, "lines")  # Adjust spacing between legend items
  ) +
  guides(fill = guide_legend(override.aes = list(size = 0.5)))  # Set the size of points in the legend




```


```{r, It_should_be_mandatory_for_all_students_from_the_Balearic_Islands_to_take_at_least_50_of_their_subjects_in_Catalan}

mod_null_It_should_be_mandatory_for_all_students_from_the_Balearic_Islands_to_take_at_least_50_of_their_subjects_in_Catalan <- lm(It_should_be_mandatory_for_all_students_from_the_Balearic_Islands_to_take_at_least_50_of_their_subjects_in_Catalan ~ 1, data = qp_data)

mod_1_It_should_be_mandatory_for_all_students_from_the_Balearic_Islands_to_take_at_least_50_of_their_subjects_in_Catalan <- lm(It_should_be_mandatory_for_all_students_from_the_Balearic_Islands_to_take_at_least_50_of_their_subjects_in_Catalan ~ 1 + political_orientation, data = qp_data)

mod_2_It_should_be_mandatory_for_all_students_from_the_Balearic_Islands_to_take_at_least_50_of_their_subjects_in_Catalan <- lm(It_should_be_mandatory_for_all_students_from_the_Balearic_Islands_to_take_at_least_50_of_their_subjects_in_Catalan ~ 1 + political_orientation + gender, data = qp_data)

mod_3_It_should_be_mandatory_for_all_students_from_the_Balearic_Islands_to_take_at_least_50_of_their_subjects_in_Catalan <- lm(It_should_be_mandatory_for_all_students_from_the_Balearic_Islands_to_take_at_least_50_of_their_subjects_in_Catalan ~ 1 + political_orientation + gender + age, data = qp_data)

mod_int_It_should_be_mandatory_for_all_students_from_the_Balearic_Islands_to_take_at_least_50_of_their_subjects_in_Catalan <- lm(It_should_be_mandatory_for_all_students_from_the_Balearic_Islands_to_take_at_least_50_of_their_subjects_in_Catalan ~ 1 + political_orientation + gender + age + political_orientation:gender:age, data = qp_data)

summary(mod_null_It_should_be_mandatory_for_all_students_from_the_Balearic_Islands_to_take_at_least_50_of_their_subjects_in_Catalan)
summary(mod_1_It_should_be_mandatory_for_all_students_from_the_Balearic_Islands_to_take_at_least_50_of_their_subjects_in_Catalan)
summary(mod_2_It_should_be_mandatory_for_all_students_from_the_Balearic_Islands_to_take_at_least_50_of_their_subjects_in_Catalan)
summary(mod_3_It_should_be_mandatory_for_all_students_from_the_Balearic_Islands_to_take_at_least_50_of_their_subjects_in_Catalan)
summary(mod_int_It_should_be_mandatory_for_all_students_from_the_Balearic_Islands_to_take_at_least_50_of_their_subjects_in_Catalan)

anova(mod_null_It_should_be_mandatory_for_all_students_from_the_Balearic_Islands_to_take_at_least_50_of_their_subjects_in_Catalan, mod_1_It_should_be_mandatory_for_all_students_from_the_Balearic_Islands_to_take_at_least_50_of_their_subjects_in_Catalan, mod_2_It_should_be_mandatory_for_all_students_from_the_Balearic_Islands_to_take_at_least_50_of_their_subjects_in_Catalan, mod_3_It_should_be_mandatory_for_all_students_from_the_Balearic_Islands_to_take_at_least_50_of_their_subjects_in_Catalan, mod_int_It_should_be_mandatory_for_all_students_from_the_Balearic_Islands_to_take_at_least_50_of_their_subjects_in_Catalan)

ggplot(
  data = qp_data, 
  aes(
    x = political_orientation,
    y = It_should_be_mandatory_for_all_students_from_the_Balearic_Islands_to_take_at_least_50_of_their_subjects_in_Catalan)) + 
  geom_point() + 
  geom_boxplot()
```


```{r, It_should_be_mandatory_for_all_students_from_the_Balearic_Islands_to_take_at_least_50_of_their_subjects_in_Spanish}

mod_null_It_should_be_mandatory_for_all_students_from_the_Balearic_Islands_to_take_at_least_50_of_their_subjects_in_Spanish <- lm(It_should_be_mandatory_for_all_students_from_the_Balearic_Islands_to_take_at_least_50_of_their_subjects_in_Spanish ~ 1, data = qp_data)

mod_1_It_should_be_mandatory_for_all_students_from_the_Balearic_Islands_to_take_at_least_50_of_their_subjects_in_Spanish <- lm(It_should_be_mandatory_for_all_students_from_the_Balearic_Islands_to_take_at_least_50_of_their_subjects_in_Spanish ~ 1 + political_orientation, data = qp_data)

mod_2_It_should_be_mandatory_for_all_students_from_the_Balearic_Islands_to_take_at_least_50_of_their_subjects_in_Spanish <- lm(It_should_be_mandatory_for_all_students_from_the_Balearic_Islands_to_take_at_least_50_of_their_subjects_in_Spanish ~ 1 + political_orientation + gender, data = qp_data)

mod_3_It_should_be_mandatory_for_all_students_from_the_Balearic_Islands_to_take_at_least_50_of_their_subjects_in_Spanish <- lm(It_should_be_mandatory_for_all_students_from_the_Balearic_Islands_to_take_at_least_50_of_their_subjects_in_Spanish ~ 1 + political_orientation + gender + age, data = qp_data)

mod_int_It_should_be_mandatory_for_all_students_from_the_Balearic_Islands_to_take_at_least_50_of_their_subjects_in_Spanish <- lm(It_should_be_mandatory_for_all_students_from_the_Balearic_Islands_to_take_at_least_50_of_their_subjects_in_Spanish ~ 1 + political_orientation + gender + age + political_orientation:gender:age, data = qp_data)

summary(mod_null_It_should_be_mandatory_for_all_students_from_the_Balearic_Islands_to_take_at_least_50_of_their_subjects_in_Spanish)
summary(mod_1_It_should_be_mandatory_for_all_students_from_the_Balearic_Islands_to_take_at_least_50_of_their_subjects_in_Spanish)
summary(mod_2_It_should_be_mandatory_for_all_students_from_the_Balearic_Islands_to_take_at_least_50_of_their_subjects_in_Spanish)
summary(mod_3_It_should_be_mandatory_for_all_students_from_the_Balearic_Islands_to_take_at_least_50_of_their_subjects_in_Spanish)
summary(mod_int_It_should_be_mandatory_for_all_students_from_the_Balearic_Islands_to_take_at_least_50_of_their_subjects_in_Spanish)

anova(mod_null_It_should_be_mandatory_for_all_students_from_the_Balearic_Islands_to_take_at_least_50_of_their_subjects_in_Spanish, mod_1_It_should_be_mandatory_for_all_students_from_the_Balearic_Islands_to_take_at_least_50_of_their_subjects_in_Spanish, mod_2_It_should_be_mandatory_for_all_students_from_the_Balearic_Islands_to_take_at_least_50_of_their_subjects_in_Spanish, mod_3_It_should_be_mandatory_for_all_students_from_the_Balearic_Islands_to_take_at_least_50_of_their_subjects_in_Spanish, mod_int_It_should_be_mandatory_for_all_students_from_the_Balearic_Islands_to_take_at_least_50_of_their_subjects_in_Spanish)

ggplot(
  data = qp_data, 
  aes(
    x = political_orientation,
    y = It_should_be_mandatory_for_all_students_from_the_Balearic_Islands_to_take_at_least_50_of_their_subjects_in_Spanish, fill = political_orientation)) + 
  geom_point() + 
  geom_boxplot() +
  labs(x = "Political orientation", y = "Mandatory for all students to take at least 50% of the subjects in Spanish", fill = "Political Orientation") +
    scale_fill_manual(values = c("indianred2", "indianred2", "indianred2", "cornflowerblue", "cornflowerblue", "cornflowerblue"))

ggplot(
  data = qp_data, 
  aes(
    x = political_orientation,
    y = It_should_be_mandatory_for_all_students_from_the_Balearic_Islands_to_take_at_least_50_of_their_subjects_in_Spanish, 
    fill = political_orientation)) + 
  geom_point(size = 1) +  # Set the size of the points on the plot
  stat_summary(fun.data = mean_se, geom = "pointrange", pch = 23, size = 1) +
  labs(x = "Political orientation", y = "Mandatory to take 50% of the subjects in Spanish", fill = "Political Orientation") +
  scale_fill_manual(values = c("indianred2", "indianred2", "indianred2", "cornflowerblue", "cornflowerblue", "cornflowerblue")) +
  theme(
    legend.key.size = unit(1, "lines"),  # Set the size of the legend key
    legend.key.width = unit(1.5, "lines"),  # Set the width of the legend key
    legend.spacing.x = unit(0.5, "lines")  # Adjust spacing between legend items
  ) +
  guides(fill = guide_legend(override.aes = list(size = 0.5)))  # Set the size of points in the legend


```

```{r, Catalan is a rural language}

mod_null_Catalan_is_a_rural_language <- lm(Catalan_is_a_rural_language ~ 1, data = qp_data)

mod_1_Catalan_is_a_rural_language <- lm(Catalan_is_a_rural_language ~ 1 + political_orientation, data = qp_data)

mod_2_Catalan_is_a_rural_language <- lm(Catalan_is_a_rural_language ~ 1 + political_orientation + gender, data = qp_data)

mod_3_Catalan_is_a_rural_language <- lm(Catalan_is_a_rural_language ~ 1 + political_orientation + gender + age, data = qp_data)

mod_int_Catalan_is_a_rural_language <- lm(Catalan_is_a_rural_language ~ 1 + political_orientation + gender + age + political_orientation:gender:age, data = qp_data)

summary(mod_null_Catalan_is_a_rural_language)
summary(mod_1_Catalan_is_a_rural_language)
summary(mod_2_Catalan_is_a_rural_language)
summary(mod_3_Catalan_is_a_rural_language)
summary(mod_int_Catalan_is_a_rural_language)

anova(mod_null_Catalan_is_a_rural_language, mod_1_Catalan_is_a_rural_language, mod_2_Catalan_is_a_rural_language, mod_3_Catalan_is_a_rural_language, mod_int_Catalan_is_a_rural_language)

ggplot(
  data = qp_data, 
  aes(
    x = political_orientation,
    y = Catalan_is_a_rural_language)) + 
  geom_point() + 
  geom_boxplot()

```


```{r, Spanish is more fashionable than Catalan}

mod_null_Spanish_is_more_fashionable_than_Catalan <- lm(Spanish_is_more_fashionable_than_Catalan ~ 1, data = qp_data)

mod_1_Spanish_is_more_fashionable_than_Catalan <- lm(Spanish_is_more_fashionable_than_Catalan ~ 1 + political_orientation, data = qp_data)

mod_2_Spanish_is_more_fashionable_than_Catalan <- lm(Spanish_is_more_fashionable_than_Catalan ~ 1 + political_orientation + gender, data = qp_data)

mod_3_Spanish_is_more_fashionable_than_Catalan <- lm(Spanish_is_more_fashionable_than_Catalan ~ 1 + political_orientation + gender + age, data = qp_data)

mod_int_Spanish_is_more_fashionable_than_Catalan <- lm(Spanish_is_more_fashionable_than_Catalan ~ 1 + political_orientation + gender + age + political_orientation:gender:age, data = qp_data)

summary(mod_null_Spanish_is_more_fashionable_than_Catalan)
summary(mod_1_Spanish_is_more_fashionable_than_Catalan)
summary(mod_2_Spanish_is_more_fashionable_than_Catalan)
summary(mod_3_Spanish_is_more_fashionable_than_Catalan)
summary(mod_int_Spanish_is_more_fashionable_than_Catalan)

anova(mod_null_Spanish_is_more_fashionable_than_Catalan, mod_1_Spanish_is_more_fashionable_than_Catalan, mod_2_Spanish_is_more_fashionable_than_Catalan, mod_3_Spanish_is_more_fashionable_than_Catalan, mod_int_Spanish_is_more_fashionable_than_Catalan)

ggplot(
  data = qp_data, 
  aes(
    x = political_orientation,
    y = Spanish_is_more_fashionable_than_Catalan)) + 
  geom_point() + 
  geom_boxplot()

```

```{r, For_healthcare_staff_it_is_more_important_to_know_Catalan_than_Spanish}

mod_null_For_healthcare_staff_it_is_more_important_to_know_Catalan_than_Spanish <- lm(For_healthcare_staff_it_is_more_important_to_know_Catalan_than_Spanish ~ 1, data = qp_data)

mod_1_For_healthcare_staff_it_is_more_important_to_know_Catalan_than_Spanish <- lm(For_healthcare_staff_it_is_more_important_to_know_Catalan_than_Spanish ~ 1 + political_orientation, data = qp_data)

mod_2_For_healthcare_staff_it_is_more_important_to_know_Catalan_than_Spanish <- lm(For_healthcare_staff_it_is_more_important_to_know_Catalan_than_Spanish ~ 1 + political_orientation + gender, data = qp_data)

mod_3_For_healthcare_staff_it_is_more_important_to_know_Catalan_than_Spanish <- lm(For_healthcare_staff_it_is_more_important_to_know_Catalan_than_Spanish ~ 1 + political_orientation + gender + age, data = qp_data)

mod_int_For_healthcare_staff_it_is_more_important_to_know_Catalan_than_Spanish <- lm(For_healthcare_staff_it_is_more_important_to_know_Catalan_than_Spanish ~ 1 + political_orientation + gender + age + political_orientation:gender:age, data = qp_data)

summary(mod_null_For_healthcare_staff_it_is_more_important_to_know_Catalan_than_Spanish)
summary(mod_1_For_healthcare_staff_it_is_more_important_to_know_Catalan_than_Spanish)
summary(mod_2_For_healthcare_staff_it_is_more_important_to_know_Catalan_than_Spanish)
summary(mod_3_For_healthcare_staff_it_is_more_important_to_know_Catalan_than_Spanish)
summary(mod_int_For_healthcare_staff_it_is_more_important_to_know_Catalan_than_Spanish)

anova(mod_null_For_healthcare_staff_it_is_more_important_to_know_Catalan_than_Spanish, mod_1_For_healthcare_staff_it_is_more_important_to_know_Catalan_than_Spanish, mod_2_For_healthcare_staff_it_is_more_important_to_know_Catalan_than_Spanish, mod_3_For_healthcare_staff_it_is_more_important_to_know_Catalan_than_Spanish, mod_int_For_healthcare_staff_it_is_more_important_to_know_Catalan_than_Spanish)

ggplot(
  data = qp_data, 
  aes(
    x = political_orientation,
    y = For_healthcare_staff_it_is_more_important_to_know_Catalan_than_Spanish)) + 
  geom_point() + 
  geom_boxplot()

ggplot(
  data = qp_data, 
  aes(
    x = political_orientation,
    y = For_healthcare_staff_it_is_more_important_to_know_Catalan_than_Spanish,
    fill = political_orientation)) + 
  geom_point(size = 1) +  # Set the size of the points on the plot
  stat_summary(fun.data = mean_se, geom = "pointrange", pch = 23, size = 1) +
  labs(x = "Political orientation", y = "It is important for healthcare staff to learn Catalan") +
  scale_fill_manual(values = c("indianred2", "indianred2", "indianred2", "cornflowerblue", "cornflowerblue", "cornflowerblue")) +
  theme(
    legend.key.size = unit(1, "lines"),  # Set the size of the legend key
    legend.key.width = unit(1.5, "lines"),  # Set the width of the legend key
    legend.spacing.x = unit(0.5, "lines")  # Adjust spacing between legend items
  ) +
  guides(fill = guide_legend(override.aes = list(size = 0.5)))  # Set the size of points in the legend

```


```{r}
mod_null_For_healthcare_staff_it_is_more_important_to_know_Spanish_than_Catalan <- lm(For_healthcare_staff_it_is_more_important_to_know_Spanish_than_Catalan ~ 1, data = qp_data)

mod_1_For_healthcare_staff_it_is_more_important_to_know_Spanish_than_Catalan <- lm(For_healthcare_staff_it_is_more_important_to_know_Spanish_than_Catalan ~ 1 + political_orientation, data = qp_data)

mod_2_For_healthcare_staff_it_is_more_important_to_know_Spanish_than_Catalan <- lm(For_healthcare_staff_it_is_more_important_to_know_Spanish_than_Catalan ~ 1 + political_orientation + gender, data = qp_data)

mod_3_For_healthcare_staff_it_is_more_important_to_know_Spanish_than_Catalan <- lm(For_healthcare_staff_it_is_more_important_to_know_Spanish_than_Catalan ~ 1 + political_orientation + gender + age, data = qp_data)

mod_int_For_healthcare_staff_it_is_more_important_to_know_Spanish_than_Catalan <- lm(For_healthcare_staff_it_is_more_important_to_know_Spanish_than_Catalan ~ 1 + political_orientation + gender + age + political_orientation:gender:age, data = qp_data)

summary(mod_null_For_healthcare_staff_it_is_more_important_to_know_Spanish_than_Catalan)
summary(mod_1_For_healthcare_staff_it_is_more_important_to_know_Spanish_than_Catalan)
summary(mod_2_For_healthcare_staff_it_is_more_important_to_know_Spanish_than_Catalan)
summary(mod_3_For_healthcare_staff_it_is_more_important_to_know_Spanish_than_Catalan)
summary(mod_int_For_healthcare_staff_it_is_more_important_to_know_Spanish_than_Catalan)

anova(mod_null_For_healthcare_staff_it_is_more_important_to_know_Spanish_than_Catalan, mod_1_For_healthcare_staff_it_is_more_important_to_know_Spanish_than_Catalan, mod_2_For_healthcare_staff_it_is_more_important_to_know_Spanish_than_Catalan, mod_3_For_healthcare_staff_it_is_more_important_to_know_Spanish_than_Catalan, mod_int_For_healthcare_staff_it_is_more_important_to_know_Spanish_than_Catalan)

ggplot(
  data = qp_data, 
  aes(
    x = political_orientation,
    y = For_healthcare_staff_it_is_more_important_to_know_Spanish_than_Catalan)) + 
  geom_point() + 
  geom_boxplot()
```

```{r, Studying_Catalan_will_be_very_useful_for_me_in_the_future_to_find_a_job}

mod_null_Studying_Catalan_will_be_very_useful_for_me_in_the_future_to_find_a_job <- lm(Studying_Catalan_will_be_very_useful_for_me_in_the_future_to_find_a_job ~ 1, data = qp_data)

mod_1_Studying_Catalan_will_be_very_useful_for_me_in_the_future_to_find_a_job <- lm(Studying_Catalan_will_be_very_useful_for_me_in_the_future_to_find_a_job ~ 1 + political_orientation, data = qp_data)

mod_2_Studying_Catalan_will_be_very_useful_for_me_in_the_future_to_find_a_job <- lm(Studying_Catalan_will_be_very_useful_for_me_in_the_future_to_find_a_job ~ 1 + political_orientation + gender, data = qp_data)

mod_3_Studying_Catalan_will_be_very_useful_for_me_in_the_future_to_find_a_job <- lm(Studying_Catalan_will_be_very_useful_for_me_in_the_future_to_find_a_job ~ 1 + political_orientation + gender + age, data = qp_data)

mod_int_Studying_Catalan_will_be_very_useful_for_me_in_the_future_to_find_a_job <- lm(Studying_Catalan_will_be_very_useful_for_me_in_the_future_to_find_a_job ~ 1 + political_orientation + gender + age + political_orientation:gender:age, data = qp_data)

summary(mod_null_Studying_Catalan_will_be_very_useful_for_me_in_the_future_to_find_a_job)
summary(mod_1_Studying_Catalan_will_be_very_useful_for_me_in_the_future_to_find_a_job)
summary(mod_2_Studying_Catalan_will_be_very_useful_for_me_in_the_future_to_find_a_job)
summary(mod_3_Studying_Catalan_will_be_very_useful_for_me_in_the_future_to_find_a_job)
summary(mod_int_Studying_Catalan_will_be_very_useful_for_me_in_the_future_to_find_a_job)

anova(mod_null_Studying_Catalan_will_be_very_useful_for_me_in_the_future_to_find_a_job, mod_1_Studying_Catalan_will_be_very_useful_for_me_in_the_future_to_find_a_job, mod_2_Studying_Catalan_will_be_very_useful_for_me_in_the_future_to_find_a_job, mod_3_Studying_Catalan_will_be_very_useful_for_me_in_the_future_to_find_a_job, mod_int_Studying_Catalan_will_be_very_useful_for_me_in_the_future_to_find_a_job)

ggplot(
  data = qp_data, 
  aes(
    x = political_orientation,
    y = Studying_Catalan_will_be_very_useful_for_me_in_the_future_to_find_a_job)) + 
  geom_point() + 
  geom_boxplot()

```


```{r}
# Sample data
df <- data.frame(original_column = c(1, 2, 3, 4, 5))

# Rename the column
names(qp_data)[names(qp_data) == "Studying_Spsnish_will_be_very_useful_for_me_in_the_future_to_find_a_job"] <- "Studying_Spanish_will_be_very_useful_for_me_in_the_future_to_find_a_job"

# Display the modified data frame
print(df)
```


```{r}
mod_null_Studying_Spanish_will_be_very_useful_for_me_in_the_future_to_find_a_job <- lm(Studying_Spanish_will_be_very_useful_for_me_in_the_future_to_find_a_job ~ 1, data = qp_data)

mod_1_Studying_Spanish_will_be_very_useful_for_me_in_the_future_to_find_a_job <- lm(Studying_Spanish_will_be_very_useful_for_me_in_the_future_to_find_a_job ~ 1 + political_orientation, data = qp_data)

mod_2_Studying_Spanish_will_be_very_useful_for_me_in_the_future_to_find_a_job <- lm(Studying_Spanish_will_be_very_useful_for_me_in_the_future_to_find_a_job ~ 1 + political_orientation + gender, data = qp_data)

mod_3_Studying_Spanish_will_be_very_useful_for_me_in_the_future_to_find_a_job <- lm(Studying_Spanish_will_be_very_useful_for_me_in_the_future_to_find_a_job ~ 1 + political_orientation + gender + age, data = qp_data)

mod_int_Studying_Spanish_will_be_very_useful_for_me_in_the_future_to_find_a_job <- lm(Studying_Spanish_will_be_very_useful_for_me_in_the_future_to_find_a_job ~ 1 + political_orientation + gender + age + political_orientation:gender:age, data = qp_data)

summary(mod_null_Studying_Spanish_will_be_very_useful_for_me_in_the_future_to_find_a_job)
summary(mod_1_Studying_Spanish_will_be_very_useful_for_me_in_the_future_to_find_a_job)
summary(mod_2_Studying_Spanish_will_be_very_useful_for_me_in_the_future_to_find_a_job)
summary(mod_3_Studying_Spanish_will_be_very_useful_for_me_in_the_future_to_find_a_job)
summary(mod_int_Studying_Spanish_will_be_very_useful_for_me_in_the_future_to_find_a_job)

anova(mod_null_Studying_Spanish_will_be_very_useful_for_me_in_the_future_to_find_a_job, mod_1_Studying_Spanish_will_be_very_useful_for_me_in_the_future_to_find_a_job, mod_2_Studying_Spanish_will_be_very_useful_for_me_in_the_future_to_find_a_job, mod_3_Studying_Spanish_will_be_very_useful_for_me_in_the_future_to_find_a_job, mod_int_Studying_Spanish_will_be_very_useful_for_me_in_the_future_to_find_a_job)

ggplot(
  data = qp_data, 
  aes(
    x = political_orientation,
    y = Studying_Spanish_will_be_very_useful_for_me_in_the_future_to_find_a_job)) + 
  geom_point() + 
  geom_boxplot()
```

```{r, It_is_necessary_to_learn_Catalan_to_fully_integrate_in_the_Balearic_Islands}

mod_null_It_is_necessary_to_learn_Catalan_to_fully_integrate_in_the_Balearic_Islands <- lm(It_is_necessary_to_learn_Catalan_to_fully_integrate_in_the_Balearic_Islands ~ 1, data = qp_data)

mod_1_It_is_necessary_to_learn_Catalan_to_fully_integrate_in_the_Balearic_Islands <- lm(It_is_necessary_to_learn_Catalan_to_fully_integrate_in_the_Balearic_Islands ~ 1 + political_orientation, data = qp_data)

mod_2_It_is_necessary_to_learn_Catalan_to_fully_integrate_in_the_Balearic_Islands <- lm(It_is_necessary_to_learn_Catalan_to_fully_integrate_in_the_Balearic_Islands ~ 1 + political_orientation + gender, data = qp_data)

mod_3_It_is_necessary_to_learn_Catalan_to_fully_integrate_in_the_Balearic_Islands <- lm(It_is_necessary_to_learn_Catalan_to_fully_integrate_in_the_Balearic_Islands ~ 1 + political_orientation + gender + age, data = qp_data)

mod_int_It_is_necessary_to_learn_Catalan_to_fully_integrate_in_the_Balearic_Islands <- lm(It_is_necessary_to_learn_Catalan_to_fully_integrate_in_the_Balearic_Islands ~ 1 + political_orientation + gender + age + political_orientation:gender:age, data = qp_data)

summary(mod_null_It_is_necessary_to_learn_Catalan_to_fully_integrate_in_the_Balearic_Islands)
summary(mod_1_It_is_necessary_to_learn_Catalan_to_fully_integrate_in_the_Balearic_Islands)
summary(mod_2_It_is_necessary_to_learn_Catalan_to_fully_integrate_in_the_Balearic_Islands)
summary(mod_3_It_is_necessary_to_learn_Catalan_to_fully_integrate_in_the_Balearic_Islands)
summary(mod_int_It_is_necessary_to_learn_Catalan_to_fully_integrate_in_the_Balearic_Islands)

anova(mod_null_It_is_necessary_to_learn_Catalan_to_fully_integrate_in_the_Balearic_Islands, mod_1_It_is_necessary_to_learn_Catalan_to_fully_integrate_in_the_Balearic_Islands, mod_2_It_is_necessary_to_learn_Catalan_to_fully_integrate_in_the_Balearic_Islands, mod_3_It_is_necessary_to_learn_Catalan_to_fully_integrate_in_the_Balearic_Islands, mod_int_It_is_necessary_to_learn_Catalan_to_fully_integrate_in_the_Balearic_Islands)

ggplot(
  data = qp_data, 
  aes(
    x = political_orientation,
    y = It_is_necessary_to_learn_Catalan_to_fully_integrate_in_the_Balearic_Islands)) + 
  geom_point() + 
  geom_boxplot()

ggplot(
  data = qp_data, 
  aes(
    x = political_orientation,
    y = It_is_necessary_to_learn_Catalan_to_fully_integrate_in_the_Balearic_Islands, 
    fill = political_orientation)) + 
  geom_point(size = 1) +  # Set the size of the points on the plot
  stat_summary(fun.data = mean_se, geom = "pointrange", pch = 23, size = 1) +
  labs(x = "Political orientation", y = "Need of Catalan to integrate in the Balearic Islands", fill = "Political Orientation") +
  scale_fill_manual(values = c("indianred2", "indianred2", "indianred2", "cornflowerblue", "cornflowerblue", "cornflowerblue")) +
  theme(
    legend.key.size = unit(1, "lines"),  # Set the size of the legend key
    legend.key.width = unit(1.5, "lines"),  # Set the width of the legend key
    legend.spacing.x = unit(0.5, "lines")  # Adjust spacing between legend items
  ) +
  guides(fill = guide_legend(override.aes = list(size = 0.5)))  # Set the size of points in the legend


```

```{r, Catalan_is_the_language_that_should_predominate_in_the_Balearic_Islands}

mod_null_Catalan_is_the_language_that_should_predominate_in_the_Balearic_Islands <- lm(Catalan_is_the_language_that_should_predominate_in_the_Balearic_Islands ~ 1, data = qp_data)

mod_1_Catalan_is_the_language_that_should_predominate_in_the_Balearic_Islands <- lm(Catalan_is_the_language_that_should_predominate_in_the_Balearic_Islands ~ 1 + political_orientation, data = qp_data)

mod_2_Catalan_is_the_language_that_should_predominate_in_the_Balearic_Islands <- lm(Catalan_is_the_language_that_should_predominate_in_the_Balearic_Islands ~ 1 + political_orientation + gender, data = qp_data)

mod_3_Catalan_is_the_language_that_should_predominate_in_the_Balearic_Islands <- lm(Catalan_is_the_language_that_should_predominate_in_the_Balearic_Islands ~ 1 + political_orientation + gender + age, data = qp_data)

mod_int_Catalan_is_the_language_that_should_predominate_in_the_Balearic_Islands <- lm(Catalan_is_the_language_that_should_predominate_in_the_Balearic_Islands ~ 1 + political_orientation + gender + age + political_orientation:gender:age, data = qp_data)

summary(mod_null_Catalan_is_the_language_that_should_predominate_in_the_Balearic_Islands)
summary(mod_1_Catalan_is_the_language_that_should_predominate_in_the_Balearic_Islands)
summary(mod_2_Catalan_is_the_language_that_should_predominate_in_the_Balearic_Islands)
summary(mod_3_Catalan_is_the_language_that_should_predominate_in_the_Balearic_Islands)
summary(mod_int_Catalan_is_the_language_that_should_predominate_in_the_Balearic_Islands)

anova(mod_null_Catalan_is_the_language_that_should_predominate_in_the_Balearic_Islands, mod_1_Catalan_is_the_language_that_should_predominate_in_the_Balearic_Islands, mod_2_Catalan_is_the_language_that_should_predominate_in_the_Balearic_Islands, mod_3_Catalan_is_the_language_that_should_predominate_in_the_Balearic_Islands, mod_int_Catalan_is_the_language_that_should_predominate_in_the_Balearic_Islands)

ggplot(
  data = qp_data, 
  aes(
    x = political_orientation,
    y = Catalan_is_the_language_that_should_predominate_in_the_Balearic_Islands, fill = political_orientation)) + 
  geom_point() + 
  geom_boxplot() +
  labs(x = "Political orientation", y = "Catalan should predominate in the Balearic Islands", fill = "Political Orientation") +
    scale_fill_manual(values = c("indianred2", "indianred2", "indianred2", "cornflowerblue", "cornflowerblue", "cornflowerblue"))



ggplot(
  data = qp_data, 
  aes(
    x = political_orientation,
    y = Catalan_is_the_language_that_should_predominate_in_the_Balearic_Islands, 
    fill = political_orientation)) + 
  geom_point(size = 1) +  # Set the size of the points on the plot
  stat_summary(fun.data = mean_se, geom = "pointrange", pch = 23, size = 1) +
  labs(x = "Political orientation", y = "Catalan should predominate in the Balearic Islands", fill = "Political Orientation") +
  scale_fill_manual(values = c("indianred2", "indianred2", "indianred2", "cornflowerblue", "cornflowerblue", "cornflowerblue")) +
  theme(
    legend.key.size = unit(1, "lines"),  # Set the size of the legend key
    legend.key.width = unit(1.5, "lines"),  # Set the width of the legend key
    legend.spacing.x = unit(0.5, "lines")  # Adjust spacing between legend items
  ) +
  guides(fill = guide_legend(override.aes = list(size = 0.5)))  # Set the size of points in the legend

```

```{r, Spanish_is_the_language_that_should_predominate_in_the_Balearic_Islands}

mod_null_Spanish_is_the_language_that_should_predominate_in_the_Balearic_Islands <- lm(Spanish_is_the_language_that_should_predominate_in_the_Balearic_Islands ~ 1, data = qp_data)

mod_1_Spanish_is_the_language_that_should_predominate_in_the_Balearic_Islands <- lm(Spanish_is_the_language_that_should_predominate_in_the_Balearic_Islands ~ 1 + political_orientation, data = qp_data)

mod_2_Spanish_is_the_language_that_should_predominate_in_the_Balearic_Islands <- lm(Spanish_is_the_language_that_should_predominate_in_the_Balearic_Islands ~ 1 + political_orientation + gender, data = qp_data)

mod_3_Spanish_is_the_language_that_should_predominate_in_the_Balearic_Islands <- lm(Spanish_is_the_language_that_should_predominate_in_the_Balearic_Islands ~ 1 + political_orientation + gender + age, data = qp_data)

mod_int_Spanish_is_the_language_that_should_predominate_in_the_Balearic_Islands <- lm(Spanish_is_the_language_that_should_predominate_in_the_Balearic_Islands ~ 1 + political_orientation + gender + age + political_orientation:gender:age, data = qp_data)

summary(mod_null_Spanish_is_the_language_that_should_predominate_in_the_Balearic_Islands)
summary(mod_1_Spanish_is_the_language_that_should_predominate_in_the_Balearic_Islands)
summary(mod_2_Spanish_is_the_language_that_should_predominate_in_the_Balearic_Islands)
summary(mod_3_Spanish_is_the_language_that_should_predominate_in_the_Balearic_Islands)
summary(mod_int_Spanish_is_the_language_that_should_predominate_in_the_Balearic_Islands)

anova(mod_null_Spanish_is_the_language_that_should_predominate_in_the_Balearic_Islands, mod_1_Spanish_is_the_language_that_should_predominate_in_the_Balearic_Islands, mod_2_Spanish_is_the_language_that_should_predominate_in_the_Balearic_Islands, mod_3_Spanish_is_the_language_that_should_predominate_in_the_Balearic_Islands, mod_int_Spanish_is_the_language_that_should_predominate_in_the_Balearic_Islands)

ggplot(
  data = qp_data, 
  aes(
    x = political_orientation,
    y = Spanish_is_the_language_that_should_predominate_in_the_Balearic_Islands)) + 
  geom_point() + 
  geom_boxplot()

```

```{r, Catalan_should_be_a_voluntary_subject_in_schools_and_high_schools_in_the_Balearic_Islands}

mod_null_Catalan_should_be_a_voluntary_subject_in_schools_and_high_schools_in_the_Balearic_Islands <- lm(Catalan_should_be_a_voluntary_subject_in_schools_and_high_schools_in_the_Balearic_Islands ~ 1, data = qp_data)

mod_1_Catalan_should_be_a_voluntary_subject_in_schools_and_high_schools_in_the_Balearic_Islands <- lm(Catalan_should_be_a_voluntary_subject_in_schools_and_high_schools_in_the_Balearic_Islands ~ 1 + political_orientation, data = qp_data)

mod_2_Catalan_should_be_a_voluntary_subject_in_schools_and_high_schools_in_the_Balearic_Islands <- lm(Catalan_should_be_a_voluntary_subject_in_schools_and_high_schools_in_the_Balearic_Islands ~ 1 + political_orientation + gender, data = qp_data)

mod_3_Catalan_should_be_a_voluntary_subject_in_schools_and_high_schools_in_the_Balearic_Islands <- lm(Catalan_should_be_a_voluntary_subject_in_schools_and_high_schools_in_the_Balearic_Islands ~ 1 + political_orientation + gender + age, data = qp_data)

mod_int_Catalan_should_be_a_voluntary_subject_in_schools_and_high_schools_in_the_Balearic_Islands <- lm(Catalan_should_be_a_voluntary_subject_in_schools_and_high_schools_in_the_Balearic_Islands ~ 1 + political_orientation + gender + age + political_orientation:gender:age, data = qp_data)

summary(mod_null_Catalan_should_be_a_voluntary_subject_in_schools_and_high_schools_in_the_Balearic_Islands)
summary(mod_1_Catalan_should_be_a_voluntary_subject_in_schools_and_high_schools_in_the_Balearic_Islands)
summary(mod_2_Catalan_should_be_a_voluntary_subject_in_schools_and_high_schools_in_the_Balearic_Islands)
summary(mod_3_Catalan_should_be_a_voluntary_subject_in_schools_and_high_schools_in_the_Balearic_Islands)
summary(mod_int_Catalan_should_be_a_voluntary_subject_in_schools_and_high_schools_in_the_Balearic_Islands)

anova(mod_null_Catalan_should_be_a_voluntary_subject_in_schools_and_high_schools_in_the_Balearic_Islands, mod_1_Catalan_should_be_a_voluntary_subject_in_schools_and_high_schools_in_the_Balearic_Islands, mod_2_Catalan_should_be_a_voluntary_subject_in_schools_and_high_schools_in_the_Balearic_Islands, mod_3_Catalan_should_be_a_voluntary_subject_in_schools_and_high_schools_in_the_Balearic_Islands, mod_int_Catalan_should_be_a_voluntary_subject_in_schools_and_high_schools_in_the_Balearic_Islands)

ggplot(
  data = qp_data, 
  aes(
    x = political_orientation,
    y = Catalan_should_be_a_voluntary_subject_in_schools_and_high_schools_in_the_Balearic_Islands, fill = political_orientation)) + 
  geom_point() + 
  geom_boxplot() +
  labs(x = "Political orientation", y = "Catalan should be a volunatry subject in schools in the Balearic Islands", fill = "Political Orientation") +
    scale_fill_manual(values = c("indianred2", "indianred2", "indianred2", "cornflowerblue", "cornflowerblue", "cornflowerblue"))


ggplot(
  data = qp_data, 
  aes(
    x = political_orientation,
    y = It_should_be_mandatory_for_all_students_from_the_Balearic_Islands_to_take_at_least_50_of_their_subjects_in_Spanish, 
    fill = political_orientation)) + 
  geom_point(size = 1) +  # Set the size of the points on the plot
  stat_summary(fun.data = mean_se, geom = "pointrange", pch = 23, size = 1) +
  labs(x = "Political orientation", y = "Mandatory to take 50% of the subjects in Spanish", fill = "Political Orientation") +
  scale_fill_manual(values = c("indianred2", "indianred2", "indianred2", "cornflowerblue", "cornflowerblue", "cornflowerblue")) +
  theme(
    legend.key.size = unit(1, "lines"),  # Set the size of the legend key
    legend.key.width = unit(1.5, "lines"),  # Set the width of the legend key
    legend.spacing.x = unit(0.5, "lines")  # Adjust spacing between legend items
  ) +
  guides(fill = guide_legend(override.aes = list(size = 0.5)))  # Set the size of points in the legend


```

```{r, Spanish_should_be_a_voluntary_subject_in_schools_and_high_schools_in_the_Balearic_Islands}

mod_null_Spanish_should_be_a_voluntary_subject_in_schools_and_high_schools_in_the_Balearic_Islands <- lm(Spanish_should_be_a_voluntary_subject_in_schools_and_high_schools_in_the_Balearic_Islands ~ 1, data = qp_data)

mod_1_Spanish_should_be_a_voluntary_subject_in_schools_and_high_schools_in_the_Balearic_Islands <- lm(Spanish_should_be_a_voluntary_subject_in_schools_and_high_schools_in_the_Balearic_Islands ~ 1 + political_orientation, data = qp_data)

mod_2_Spanish_should_be_a_voluntary_subject_in_schools_and_high_schools_in_the_Balearic_Islands <- lm(Spanish_should_be_a_voluntary_subject_in_schools_and_high_schools_in_the_Balearic_Islands ~ 1 + political_orientation + gender, data = qp_data)

mod_3_Spanish_should_be_a_voluntary_subject_in_schools_and_high_schools_in_the_Balearic_Islands <- lm(Spanish_should_be_a_voluntary_subject_in_schools_and_high_schools_in_the_Balearic_Islands ~ 1 + political_orientation + gender + age, data = qp_data)

mod_int_Spanish_should_be_a_voluntary_subject_in_schools_and_high_schools_in_the_Balearic_Islands <- lm(Spanish_should_be_a_voluntary_subject_in_schools_and_high_schools_in_the_Balearic_Islands ~ 1 + political_orientation + gender + age + political_orientation:gender:age, data = qp_data)

summary(mod_null_Spanish_should_be_a_voluntary_subject_in_schools_and_high_schools_in_the_Balearic_Islands)
summary(mod_1_Spanish_should_be_a_voluntary_subject_in_schools_and_high_schools_in_the_Balearic_Islands)
summary(mod_2_Spanish_should_be_a_voluntary_subject_in_schools_and_high_schools_in_the_Balearic_Islands)
summary(mod_3_Spanish_should_be_a_voluntary_subject_in_schools_and_high_schools_in_the_Balearic_Islands)
summary(mod_int_Spanish_should_be_a_voluntary_subject_in_schools_and_high_schools_in_the_Balearic_Islands)

anova(mod_null_Spanish_should_be_a_voluntary_subject_in_schools_and_high_schools_in_the_Balearic_Islands, mod_1_Spanish_should_be_a_voluntary_subject_in_schools_and_high_schools_in_the_Balearic_Islands, mod_2_Spanish_should_be_a_voluntary_subject_in_schools_and_high_schools_in_the_Balearic_Islands, mod_3_Spanish_should_be_a_voluntary_subject_in_schools_and_high_schools_in_the_Balearic_Islands, mod_int_Spanish_should_be_a_voluntary_subject_in_schools_and_high_schools_in_the_Balearic_Islands)

ggplot(
  data = qp_data, 
  aes(
    x = political_orientation,
    y = Spanish_should_be_a_voluntary_subject_in_schools_and_high_schools_in_the_Balearic_Islands, fill = political_orientation)) + 
  geom_point() + 
  geom_boxplot() +
  labs(x = "Political orientation", y = "Spanish should be a volunatry subject in schools in the Balearic Islands", fill = "Political Orientation") +
    scale_fill_manual(values = c("indianred2", "indianred2", "indianred2", "cornflowerblue", "cornflowerblue", "cornflowerblue"))

```

```{r, An_outsider_will_find_it_less_difficult_to_learn_Spanish_than_Catalan}

mod_null_An_outsider_will_find_it_less_difficult_to_learn_Spanish_than_Catalan <- lm(An_outsider_will_find_it_less_difficult_to_learn_Spanish_than_Catalan ~ 1, data = qp_data)

mod_1_An_outsider_will_find_it_less_difficult_to_learn_Spanish_than_Catalan <- lm(An_outsider_will_find_it_less_difficult_to_learn_Spanish_than_Catalan ~ 1 + political_orientation, data = qp_data)

mod_2_An_outsider_will_find_it_less_difficult_to_learn_Spanish_than_Catalan <- lm(An_outsider_will_find_it_less_difficult_to_learn_Spanish_than_Catalan ~ 1 + political_orientation + gender, data = qp_data)

mod_3_An_outsider_will_find_it_less_difficult_to_learn_Spanish_than_Catalan <- lm(An_outsider_will_find_it_less_difficult_to_learn_Spanish_than_Catalan ~ 1 + political_orientation + gender + age, data = qp_data)

mod_int_An_outsider_will_find_it_less_difficult_to_learn_Spanish_than_Catalan <- lm(An_outsider_will_find_it_less_difficult_to_learn_Spanish_than_Catalan ~ 1 + political_orientation + gender + age + political_orientation:gender:age, data = qp_data)

summary(mod_null_An_outsider_will_find_it_less_difficult_to_learn_Spanish_than_Catalan)
summary(mod_1_An_outsider_will_find_it_less_difficult_to_learn_Spanish_than_Catalan)
summary(mod_2_An_outsider_will_find_it_less_difficult_to_learn_Spanish_than_Catalan)
summary(mod_3_An_outsider_will_find_it_less_difficult_to_learn_Spanish_than_Catalan)
summary(mod_int_An_outsider_will_find_it_less_difficult_to_learn_Spanish_than_Catalan)

anova(mod_null_An_outsider_will_find_it_less_difficult_to_learn_Spanish_than_Catalan, mod_1_An_outsider_will_find_it_less_difficult_to_learn_Spanish_than_Catalan, mod_2_An_outsider_will_find_it_less_difficult_to_learn_Spanish_than_Catalan, mod_3_An_outsider_will_find_it_less_difficult_to_learn_Spanish_than_Catalan, mod_int_An_outsider_will_find_it_less_difficult_to_learn_Spanish_than_Catalan)

ggplot(
  data = qp_data, 
  aes(
    x = political_orientation,
    y = An_outsider_will_find_it_less_difficult_to_learn_Spanish_than_Catalan)) + 
  geom_point() + 
  geom_boxplot()


ggplot(
  data = qp_data, 
  aes(
    x = political_orientation,
    y = An_outsider_will_find_it_less_difficult_to_learn_Spanish_than_Catalan, 
    fill = political_orientation)) + 
  geom_point(size = 1) +  # Set the size of the points on the plot
  stat_summary(fun.data = mean_se, geom = "pointrange", pch = 23, size = 1) +
  labs(x = "Political orientation", y = "An outsider will find it less difficult to learn Spanish", fill = "Political Orientation") +
  scale_fill_manual(values = c("indianred2", "indianred2", "indianred2", "cornflowerblue", "cornflowerblue", "cornflowerblue")) +
  theme(
    legend.key.size = unit(1, "lines"),  # Set the size of the legend key
    legend.key.width = unit(1.5, "lines"),  # Set the width of the legend key
    legend.spacing.x = unit(0.5, "lines")  # Adjust spacing between legend items
  ) +
  guides(fill = guide_legend(override.aes = list(size = 0.5)))  # Set the size of points in the legend

```

```{r, All_people_living_in_the_Balearic_Islands_should_know_Catalan_and_Spanish}

mod_null_All_people_living_in_the_Balearic_Islands_should_know_Catalan_and_Spanish <- lm(All_people_living_in_the_Balearic_Islands_should_know_Catalan_and_Spanish ~ 1, data = qp_data)

mod_1_All_people_living_in_the_Balearic_Islands_should_know_Catalan_and_Spanish <- lm(All_people_living_in_the_Balearic_Islands_should_know_Catalan_and_Spanish ~ 1 + political_orientation, data = qp_data)

mod_2_All_people_living_in_the_Balearic_Islands_should_know_Catalan_and_Spanish <- lm(All_people_living_in_the_Balearic_Islands_should_know_Catalan_and_Spanish ~ 1 + political_orientation + gender, data = qp_data)

mod_3_All_people_living_in_the_Balearic_Islands_should_know_Catalan_and_Spanish <- lm(All_people_living_in_the_Balearic_Islands_should_know_Catalan_and_Spanish ~ 1 + political_orientation + gender + age, data = qp_data)

mod_int_All_people_living_in_the_Balearic_Islands_should_know_Catalan_and_Spanish <- lm(All_people_living_in_the_Balearic_Islands_should_know_Catalan_and_Spanish ~ 1 + political_orientation + gender + age + political_orientation:gender:age, data = qp_data)

summary(mod_null_All_people_living_in_the_Balearic_Islands_should_know_Catalan_and_Spanish)
summary(mod_1_All_people_living_in_the_Balearic_Islands_should_know_Catalan_and_Spanish)
summary(mod_2_All_people_living_in_the_Balearic_Islands_should_know_Catalan_and_Spanish)
summary(mod_3_All_people_living_in_the_Balearic_Islands_should_know_Catalan_and_Spanish)
summary(mod_int_All_people_living_in_the_Balearic_Islands_should_know_Catalan_and_Spanish)

anova(mod_null_All_people_living_in_the_Balearic_Islands_should_know_Catalan_and_Spanish, mod_1_All_people_living_in_the_Balearic_Islands_should_know_Catalan_and_Spanish, mod_2_All_people_living_in_the_Balearic_Islands_should_know_Catalan_and_Spanish, mod_3_All_people_living_in_the_Balearic_Islands_should_know_Catalan_and_Spanish, mod_int_All_people_living_in_the_Balearic_Islands_should_know_Catalan_and_Spanish)

ggplot(
  data = qp_data, 
  aes(
    x = political_orientation,
    y = All_people_living_in_the_Balearic_Islands_should_know_Catalan_and_Spanish, fill = political_orientation)) + 
  geom_point() + 
  geom_boxplot() +
  labs(x = "Political orientation", y = "People living in the Balearic Islands should know Catalan and Spanish", fill = "Political Orientation") +
    scale_fill_manual(values = c("indianred2", "indianred2", "indianred2", "cornflowerblue", "cornflowerblue", "cornflowerblue"))

```


```{r, Fewer_and_fewer_people_know_Catalan}

mod_null_Fewer_and_fewer_people_know_Catalan <- lm(Fewer_and_fewer_people_know_Catalan ~ 1, data = qp_data)

mod_1_Fewer_and_fewer_people_know_Catalan <- lm(Fewer_and_fewer_people_know_Catalan ~ 1 + political_orientation, data = qp_data)

mod_2_Fewer_and_fewer_people_know_Catalan <- lm(Fewer_and_fewer_people_know_Catalan ~ 1 + political_orientation + gender, data = qp_data)

mod_3_Fewer_and_fewer_people_know_Catalan <- lm(Fewer_and_fewer_people_know_Catalan ~ 1 + political_orientation + gender + age, data = qp_data)

mod_int_Fewer_and_fewer_people_know_Catalan <- lm(Fewer_and_fewer_people_know_Catalan ~ 1 + political_orientation + gender + age + political_orientation:gender:age, data = qp_data)

summary(mod_null_Fewer_and_fewer_people_know_Catalan)
summary(mod_1_Fewer_and_fewer_people_know_Catalan)
summary(mod_2_Fewer_and_fewer_people_know_Catalan)
summary(mod_3_Fewer_and_fewer_people_know_Catalan)
summary(mod_int_Fewer_and_fewer_people_know_Catalan)

anova(mod_null_Fewer_and_fewer_people_know_Catalan, mod_1_Fewer_and_fewer_people_know_Catalan, mod_2_Fewer_and_fewer_people_know_Catalan, mod_3_Fewer_and_fewer_people_know_Catalan, mod_int_Fewer_and_fewer_people_know_Catalan)

ggplot(
  data = qp_data, 
  aes(
    x = political_orientation,
    y = Fewer_and_fewer_people_know_Catalan, fill = political_orientation)) + 
  geom_point() + 
  geom_boxplot() +
  labs(x = "Political orientation", y = "Fewer and fewer people know Catalan", fill = "Political Orientation") +
    scale_fill_manual(values = c("indianred2", "indianred2", "indianred2", "cornflowerblue", "cornflowerblue", "cornflowerblue"))

ggplot(
  data = qp_data, 
  aes(
    x = political_orientation,
    y = Fewer_and_fewer_people_know_Catalan, 
    fill = political_orientation)) + 
  geom_point(size = 1) +  # Set the size of the points on the plot
  stat_summary(fun.data = mean_se, geom = "pointrange", pch = 23, size = 1) +
  labs(x = "Political orientation", y = "Fewer and fewer people know Catalan", fill = "Political Orientation") +
  scale_fill_manual(values = c("indianred2", "indianred2", "indianred2", "cornflowerblue", "cornflowerblue", "cornflowerblue")) +
  theme(
    legend.key.size = unit(1, "lines"),  # Set the size of the legend key
    legend.key.width = unit(1.5, "lines"),  # Set the width of the legend key
    legend.spacing.x = unit(0.5, "lines")  # Adjust spacing between legend items
  ) +
  guides(fill = guide_legend(override.aes = list(size = 0.5)))  # Set the size of points in the legend



```


```{r}
mod_null_Fewer_and_fewer_people_know_Spanish <- lm(Fewer_and_fewer_people_know_Spanish ~ 1, data = qp_data)

mod_1_Fewer_and_fewer_people_know_Spanish <- lm(Fewer_and_fewer_people_know_Spanish ~ 1 + political_orientation, data = qp_data)

mod_2_Fewer_and_fewer_people_know_Spanish <- lm(Fewer_and_fewer_people_know_Spanish ~ 1 + political_orientation + gender, data = qp_data)

mod_3_Fewer_and_fewer_people_know_Spanish <- lm(Fewer_and_fewer_people_know_Spanish ~ 1 + political_orientation + gender + age, data = qp_data)

mod_int_Fewer_and_fewer_people_know_Spanish <- lm(Fewer_and_fewer_people_know_Spanish ~ 1 + political_orientation + gender + age + political_orientation:gender:age, data = qp_data)

summary(mod_null_Fewer_and_fewer_people_know_Spanish)
summary(mod_1_Fewer_and_fewer_people_know_Spanish)
summary(mod_2_Fewer_and_fewer_people_know_Spanish)
summary(mod_3_Fewer_and_fewer_people_know_Spanish)
summary(mod_int_Fewer_and_fewer_people_know_Spanish)

anova(mod_null_Fewer_and_fewer_people_know_Spanish, mod_1_Fewer_and_fewer_people_know_Spanish, mod_2_Fewer_and_fewer_people_know_Spanish, mod_3_Fewer_and_fewer_people_know_Spanish, mod_int_Fewer_and_fewer_people_know_Spanish)

ggplot(
  data = qp_data, 
  aes(
    x = political_orientation,
    y = Fewer_and_fewer_people_know_Spanish)) + 
  geom_point() + 
  geom_boxplot()
```

```{r, Catalan_serves_for_some_areas_and_Spanish_for_others}

mod_null_Catalan_serves_for_some_areas_and_Spanish_for_others <- lm(Catalan_serves_for_some_areas_and_Spanish_for_others ~ 1, data = qp_data)

mod_1_Catalan_serves_for_some_areas_and_Spanish_for_others <- lm(Catalan_serves_for_some_areas_and_Spanish_for_others ~ 1 + political_orientation, data = qp_data)

mod_2_Catalan_serves_for_some_areas_and_Spanish_for_others <- lm(Catalan_serves_for_some_areas_and_Spanish_for_others ~ 1 + political_orientation + gender, data = qp_data)

mod_3_Catalan_serves_for_some_areas_and_Spanish_for_others <- lm(Catalan_serves_for_some_areas_and_Spanish_for_others ~ 1 + political_orientation + gender + age, data = qp_data)

mod_int_Catalan_serves_for_some_areas_and_Spanish_for_others <- lm(Catalan_serves_for_some_areas_and_Spanish_for_others ~ 1 + political_orientation + gender + age + political_orientation:gender:age, data = qp_data)

summary(mod_null_Catalan_serves_for_some_areas_and_Spanish_for_others)
summary(mod_1_Catalan_serves_for_some_areas_and_Spanish_for_others)
summary(mod_2_Catalan_serves_for_some_areas_and_Spanish_for_others)
summary(mod_3_Catalan_serves_for_some_areas_and_Spanish_for_others)
summary(mod_int_Catalan_serves_for_some_areas_and_Spanish_for_others)

anova(mod_null_Catalan_serves_for_some_areas_and_Spanish_for_others, mod_1_Catalan_serves_for_some_areas_and_Spanish_for_others, mod_2_Catalan_serves_for_some_areas_and_Spanish_for_others, mod_3_Catalan_serves_for_some_areas_and_Spanish_for_others, mod_int_Catalan_serves_for_some_areas_and_Spanish_for_others)

ggplot(
  data = qp_data, 
  aes(
    x = political_orientation,
    y = Catalan_serves_for_some_areas_and_Spanish_for_others)) + 
  geom_point() + 
  geom_boxplot()
```

```{r, Catalan_must_be_a_requirement_to_hold_a_job_in_the_public_administration}

mod_null_Catalan_must_be_a_requirement_to_hold_a_job_in_the_public_administration <- lm(Catalan_must_be_a_requirement_to_hold_a_job_in_the_public_administration ~ 1, data = qp_data)

mod_1_Catalan_must_be_a_requirement_to_hold_a_job_in_the_public_administration <- lm(Catalan_must_be_a_requirement_to_hold_a_job_in_the_public_administration ~ 1 + political_orientation, data = qp_data)

mod_2_Catalan_must_be_a_requirement_to_hold_a_job_in_the_public_administration <- lm(Catalan_must_be_a_requirement_to_hold_a_job_in_the_public_administration ~ 1 + political_orientation + gender, data = qp_data)

mod_3_Catalan_must_be_a_requirement_to_hold_a_job_in_the_public_administration <- lm(Catalan_must_be_a_requirement_to_hold_a_job_in_the_public_administration ~ 1 + political_orientation + gender + age, data = qp_data)

mod_int_Catalan_must_be_a_requirement_to_hold_a_job_in_the_public_administration <- lm(Catalan_must_be_a_requirement_to_hold_a_job_in_the_public_administration ~ 1 + political_orientation + gender + age + political_orientation:gender:age, data = qp_data)

summary(mod_null_Catalan_must_be_a_requirement_to_hold_a_job_in_the_public_administration)
summary(mod_1_Catalan_must_be_a_requirement_to_hold_a_job_in_the_public_administration)
summary(mod_2_Catalan_must_be_a_requirement_to_hold_a_job_in_the_public_administration)
summary(mod_3_Catalan_must_be_a_requirement_to_hold_a_job_in_the_public_administration)
summary(mod_int_Catalan_must_be_a_requirement_to_hold_a_job_in_the_public_administration)

anova(mod_null_Catalan_must_be_a_requirement_to_hold_a_job_in_the_public_administration, mod_1_Catalan_must_be_a_requirement_to_hold_a_job_in_the_public_administration, mod_2_Catalan_must_be_a_requirement_to_hold_a_job_in_the_public_administration, mod_3_Catalan_must_be_a_requirement_to_hold_a_job_in_the_public_administration, mod_int_Catalan_must_be_a_requirement_to_hold_a_job_in_the_public_administration)

ggplot(
  data = qp_data, 
  aes(
    x = political_orientation,
    y = Catalan_must_be_a_requirement_to_hold_a_job_in_the_public_administration, fill = political_orientation)) + 
  geom_point() + 
  geom_boxplot() +
  labs(x = "Political orientation", y = "Catalan must be a requirement to hold a job in the public administration", fill = "Political Orientation") +
    scale_fill_manual(values = c("indianred2", "indianred2", "indianred2", "cornflowerblue", "cornflowerblue", "cornflowerblue"))



ggplot(
  data = qp_data, 
  aes(
    x = political_orientation,
    y = Catalan_must_be_a_requirement_to_hold_a_job_in_the_public_administration
    fill = political_orientation)) + 
  geom_point(size = 1) +  # Set the size of the points on the plot
  stat_summary(fun.data = mean_se, geom = "pointrange", pch = 23, size = 1) +
  labs(x = "Political orientation", y = "Requiremen to hold a job in the public administration", fill = "Political Orientation") +
  scale_fill_manual(values = c("indianred2", "indianred2", "indianred2", "cornflowerblue", "cornflowerblue", "cornflowerblue")) +
  theme(
    legend.key.size = unit(1, "lines"),  # Set the size of the legend key
    legend.key.width = unit(1.5, "lines"),  # Set the width of the legend key
    legend.spacing.x = unit(0.5, "lines")  # Adjust spacing between legend items
  ) +
  guides(fill = guide_legend(override.aes = list(size = 0.5)))  # Set the size of points in the legend


```

```{r}

qp_data %>%
  filter(mother_tongue != "Other(s)") %>%
  ggplot(aes(x = gender, fill = mother_tongue)) +
  geom_bar(stat = "count", position = "dodge")


qp_data %>%
  filter(mother_tongue != "Other(s)") %>%
  ggplot(aes(x = gender, fill = mother_tongue)) +
  geom_bar(stat = "count", position = "stack")

qp_data %>%
  filter(mother_tongue != "Other(s)") %>%
  ggplot(aes(x = political_orientation, fill = mother_tongue)) +
  geom_bar(stat = "count", position = "fill") +
  labs(y = "Count", fill = "Mother tongue", x = "Political orientation")


qp_data %>%
  ggplot(aes(x = political_orientation, fill = mother_tongue)) +
  geom_bar(stat = "count", position = "fill")


qp_data %>%
  filter(mother_tongue != "Other(s)") %>%
  ggplot(aes(x = gender, fill = mother_tongue)) +
  geom_bar(stat = "count", position = "fill") +
  facet_grid(~ political_orientation)


library(ggplot2)

# Assuming qp_data is your data frame

# Aggregate the data by political orientation and mother tongue
agg_data <- qp_data %>%
  filter(mother_tongue != "Other(s)") %>%
  group_by(political_orientation, mother_tongue) %>%
  summarise(count = n()) %>%
  mutate(percent = count / sum(count)) # Calculate percentage

# Plotting
ggplot(agg_data, aes(x = political_orientation, y = percent, fill = mother_tongue)) +
  geom_bar(stat = "identity", position = "fill") +
  ylab("Percentage") +
  facet_wrap(~ mother_tongue) + # Facet by mother tongue
  theme(axis.text.x = element_text(angle = 45, hjust = 1)) # Rotate x-axis labels if necessary





```


```{r}

qp_data %>%
  ggplot(aes(x = gender, fill = catalan_proficiency_speak)) +
  geom_bar(stat = "count", position = "dodge")

qp_data %>%
  ggplot(aes(x = catalan_proficiency_speak, fill = gender)) +
  geom_bar(stat = "count", position = "dodge")

```



```{r, language use with different people}

qp_data %>%
  filter(language_used_with_father != "Others") %>%
  ggplot(aes(x = language_used_with_father, fill = gender)) +
  geom_bar(stat = "count", position = "dodge")

qp_data %>%
  filter(language_used_with_father != "Others") %>%
  ggplot(aes(x = gender, fill = language_used_with_father)) +
  geom_bar(stat = "count", position = "dodge")

qp_data %>%
  filter(language_used_with_mother != "Others") %>%
  filter(language_used_with_mother != "N/A") %>%
  ggplot(aes(x = gender, fill = language_used_with_mother)) +
  geom_bar(stat = "count", position = "dodge")

qp_data %>%
  filter(language_used_with_sibilings != "Others") %>%
  filter(language_used_with_sibilings != "N/A") %>%
  ggplot(aes(x = gender, fill = language_used_with_sibilings)) +
  geom_bar(stat = "count", position = "dodge")

qp_data %>%
  filter(language_used_with_grandparents != "Others") %>%
  filter(language_used_with_grandparents != "N/A") %>%
  ggplot(aes(x = gender, fill = language_used_with_grandparents)) +
  geom_bar(stat = "count", position = "dodge")

qp_data %>%
  filter(language_used_with_friends != "Others") %>%
  filter(language_used_with_friends != "N/A") %>%
  ggplot(aes(x = gender, fill = language_used_with_friends)) +
  geom_bar(stat = "count", position = "dodge")

qp_data %>%
  filter(language_used_with_neighbours != "Others") %>%
  filter(language_used_with_neighbours != "N/A") %>%
  ggplot(aes(x = gender, fill = language_used_with_neighbours)) +
  geom_bar(stat = "count", position = "dodge")

qp_data %>%
  filter(language_used_with_partner != "Others") %>%
  filter(language_used_with_partner != "N/A") %>%
  ggplot(aes(x = gender, fill = language_used_with_partner)) +
  geom_bar(stat = "count", position = "dodge")

qp_data %>%
  filter(language_used_with_relatives != "Others") %>%
  filter(language_used_with_relatives != "N/A") %>%
  ggplot(aes(x = gender, fill = language_used_with_relatives)) +
  geom_bar(stat = "count", position = "dodge")

qp_data %>%
  filter(language_used_with_teachers != "Others") %>%
  filter(language_used_with_teachers != "N/A") %>%
  ggplot(aes(x = gender, fill = language_used_with_teachers)) +
  geom_bar(stat = "count", position = "dodge")

qp_data %>%
  filter(language_used_with_classmates != "Others") %>%
  filter(language_used_with_classmates != "N/A") %>%
  ggplot(aes(x = gender, fill = language_used_with_classmates)) +
  geom_bar(stat = "count", position = "dodge")


qp_data %>%
  filter(language_used_with_coworkers != "Others") %>%
  filter(language_used_with_coworkers != "N/A") %>%
  ggplot(aes(x = gender, fill = language_used_with_coworkers)) +
  geom_bar(stat = "count", position = "dodge")

qp_data %>%
  filter(language_used_with_immigrants != "Others") %>%
  filter(language_used_with_immigrants != "N/A") %>%
  ggplot(aes(x = gender, fill = language_used_with_immigrants)) +
  geom_bar(stat = "count", position = "dodge")

qp_data %>%
  filter(language_used_with_children != "Others") %>%
  filter(language_used_with_children != "N/A") %>%
  ggplot(aes(x = gender, fill = language_used_with_children)) +
  geom_bar(stat = "count", position = "dodge")


```

```{r, language use in different contexts}

qp_data %>%
  filter(language_watch_TV != "Others") %>%
  filter(language_watch_TV != "N/A") %>%
  ggplot(aes(x = gender, fill = language_watch_TV)) +
  geom_bar(stat = "count", position = "dodge")

qp_data %>%
  filter(language_read != "Others") %>%
  filter(language_read != "N/A") %>%
  ggplot(aes(x = gender, fill = language_read)) +
  geom_bar(stat = "count", position = "dodge")

qp_data %>%
  filter(language_music != "Others") %>%
  filter(language_music != "N/A") %>%
  ggplot(aes(x = gender, fill = language_music)) +
  geom_bar(stat = "count", position = "dodge")

qp_data %>%
  filter(language_radio != "Others") %>%
  filter(language_radio != "N/A") %>%
  ggplot(aes(x = gender, fill = language_radio)) +
  geom_bar(stat = "count", position = "dodge")


qp_data %>%
  filter(language_movies != "Others") %>%
  filter(language_movies != "N/A") %>%
  ggplot(aes(x = gender, fill = language_movies)) +
  geom_bar(stat = "count", position = "dodge")

qp_data %>%
  filter(language_small_business != "Others") %>%
  filter(language_small_business != "N/A") %>%
  ggplot(aes(x = gender, fill = language_small_business)) +
  geom_bar(stat = "count", position = "dodge")

qp_data %>%
  filter(language_large_stores != "Others") %>%
  filter(language_large_stores != "N/A") %>%
  ggplot(aes(x = gender, fill = language_large_stores)) +
  geom_bar(stat = "count", position = "dodge")

qp_data %>%
  filter(language_financial_entities != "Others") %>%
  filter(language_financial_entities != "N/A") %>%
  ggplot(aes(x = gender, fill = language_financial_entities)) +
  geom_bar(stat = "count", position = "dodge")


qp_data %>%
  filter(language_administration != "Others") %>%
  filter(language_administration != "N/A") %>%
  ggplot(aes(x = gender, fill = language_administration)) +
  geom_bar(stat = "count", position = "dodge")

qp_data %>%
  filter(language_health_care != "Others") %>%
  filter(language_health_care != "N/A") %>%
  ggplot(aes(x = gender, fill = language_health_care)) +
  geom_bar(stat = "count", position = "dodge")

qp_data %>%
  filter(language_home != "Others") %>%
  filter(language_home != "N/A") %>%
  ggplot(aes(x = gender, fill = language_home)) +
  geom_bar(stat = "count", position = "dodge")

qp_data %>%
  filter(language_work != "Others") %>%
  filter(language_work != "N/A") %>%
  ggplot(aes(x = gender, fill = language_work)) +
  geom_bar(stat = "count", position = "dodge")

qp_data %>%
  filter(language_school != "Others") %>%
  filter(language_school != "N/A") %>%
  ggplot(aes(x = gender, fill = language_school)) +
  geom_bar(stat = "count", position = "dodge")

qp_data %>%
  filter(language_count != "Others") %>%
  filter(language_count != "N/A") %>%
  ggplot(aes(x = gender, fill = language_count)) +
  geom_bar(stat = "count", position = "dodge")

qp_data %>%
  filter(language_angry != "Others") %>%
  filter(language_angry != "N/A") %>%
  ggplot(aes(x = gender, fill = language_angry)) +
  geom_bar(stat = "count", position = "dodge")


qp_data %>%
  filter(language_social_networks != "Others") %>%
  filter(language_social_networks != "N/A") %>%
  ggplot(aes(x = gender, fill = language_social_networks)) +
  geom_bar(stat = "count", position = "dodge")


qp_data %>%
  filter(language_public_transportation != "Others") %>%
  filter(language_public_transportation != "N/A") %>%
  ggplot(aes(x = gender, fill = language_public_transportation)) +
  geom_bar(stat = "count", position = "dodge")

qp_data %>%
  filter(language_phone != "Others") %>%
  filter(language_phone != "N/A") %>%
  ggplot(aes(x = gender, fill = language_phone)) +
  geom_bar(stat = "count", position = "dodge")

qp_data %>%
  filter(language_taking_notes != "Others") %>%
  filter(language_taking_notes != "N/A") %>%
  ggplot(aes(x = gender, fill = language_taking_notes)) +
  geom_bar(stat = "count", position = "dodge")

qp_data %>%
  filter(language_law_enforcement != "Others") %>%
  filter(language_law_enforcement != "N/A") %>%
  ggplot(aes(x = gender, fill = language_law_enforcement)) +
  geom_bar(stat = "count", position = "dodge")

```

```{r}

qp_data %>%
  ggplot(
    aes(x = Balearic_Islands_native_language, fill = gender)) +
  geom_bar(position = "dodge", stat = "count")

qp_data %>%
  group_by(Balearic_Islands_native_language, gender, political_orientation) %>%
  summarise(count = n()) %>%
  ggplot(aes(x = Balearic_Islands_native_language, y = count, fill = gender)) +
  geom_bar(stat = "identity", position = "stack") +
  theme(axis.text.x = element_text(angle = 45, hjust = 1)) +
  facet_grid(~ political_orientation)

qp_data %>%
  group_by(Balearic_Islands_native_language, gender, family_income) %>%
  summarise(count = n()) %>%
  ggplot(aes(x = Balearic_Islands_native_language, y = count, fill = gender)) +
  geom_bar(stat = "identity", position = "stack") +
  theme(axis.text.x = element_text(angle = 45, hjust = 1)) +
  facet_grid(~ family_income)

qp_data %>%
  filter(mother_tongue != "Other(s)") %>%
  group_by(mother_tongue, gender, political_orientation) %>%
  summarise(count = n()) %>%
  ggplot(aes(x = mother_tongue, y = count, fill = gender)) +
  geom_bar(stat = "identity", position = "stack") +
  theme(axis.text.x = element_text(angle = 45, hjust = 1)) +
  facet_grid(~ political_orientation)

qp_data %>%
  filter(mother_tongue != "Other(s)") %>%
  group_by(mother_tongue, political_orientation) %>%
  summarise(count = n()) %>%
  ggplot(aes(x = mother_tongue, y = count, fill = mother_tongue)) +
  geom_bar(stat = "identity", position = "stack") +
  theme(axis.text.x = element_text(angle = 45, hjust = 1)) +
  facet_grid(~ political_orientation)

qp_data %>%
  filter(mother_tongue != "Other(s)") %>%
  group_by(mother_tongue, political_orientation) %>%
  summarise(count = n()) %>%
  ggplot(aes(x = , y = mother_tongue, fill = mother_tongue)) +
  geom_bar(stat = "identity", position = "stack") +
  theme(axis.text.x = element_text(angle = 45, hjust = 1)) +
  facet_grid(~ political_orientation)



qp_data %>%
  ggplot(
    aes(x = Balearic_Islands_official_language, fill = gender)) +
  geom_bar(position = "dodge", stat = "count")

qp_data %>%
  group_by(Balearic_Islands_official_language, gender) %>%
  summarise(count = n()) %>%
  ggplot(aes(x = Balearic_Islands_official_language, y = count, fill = gender)) +
  geom_bar(stat = "identity", position = "stack") +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))



qp_data %>%
  ggplot(
    aes(x = Balearic_Islands_should_speak, fill = gender)) +
  geom_bar(position = "dodge", stat = "count")

qp_data %>%
  group_by(Balearic_Islands_should_speak, gender) %>%
  summarise(count = n()) %>%
  ggplot(aes(x = Balearic_Islands_should_speak, y = count, fill = gender)) +
  geom_bar(stat = "identity", position = "stack") +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))



qp_data %>%
  ggplot(
    aes(x = Balearic_Islands_language_public_administration, fill = gender)) +
  geom_bar(position = "dodge", stat = "count")

qp_data %>%
  group_by(Balearic_Islands_language_public_administration, gender) %>%
  summarise(count = n()) %>%
  ggplot(aes(x = Balearic_Islands_language_public_administration, y = count, fill = gender)) +
  geom_bar(stat = "identity", position = "stack") +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))



qp_data %>%
  ggplot(
    aes(x = Balearic_Islands_language_health_care, fill = gender)) +
  geom_bar(position = "dodge", stat = "count")

qp_data %>%
  group_by(Balearic_Islands_language_health_care, gender) %>%
  summarise(count = n()) %>%
  ggplot(aes(x = Balearic_Islands_language_health_care, y = count, fill = gender)) +
  geom_bar(stat = "identity", position = "stack") +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))



qp_data %>%
  ggplot(
    aes(x = Balearic_Islands_language_media, fill = gender)) +
  geom_bar(position = "dodge", stat = "count")

qp_data %>%
  group_by(Balearic_Islands_language_media, gender) %>%
  summarise(count = n()) %>%
  ggplot(aes(x = Balearic_Islands_language_media, y = count, fill = gender)) +
  geom_bar(stat = "identity", position = "stack") +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))



qp_data %>%
  ggplot(
    aes(x = Balearic_Islands_language_institutional_acts, fill = gender)) +
  geom_bar(position = "dodge", stat = "count")

qp_data %>%
  group_by(Balearic_Islands_language_institutional_acts, gender) %>%
  summarise(count = n()) %>%
  ggplot(aes(x = Balearic_Islands_language_institutional_acts, y = count, fill = gender)) +
  geom_bar(stat = "identity", position = "stack") +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))



qp_data %>%
  ggplot(
    aes(x = Balearic_Islands_host_language_immigrants, fill = gender)) +
  geom_bar(position = "dodge", stat = "count")

qp_data %>%
  group_by(Balearic_Islands_host_language_immigrants, gender) %>%
  summarise(count = n()) %>%
  ggplot(aes(x = Balearic_Islands_host_language_immigrants, y = count, fill = gender)) +
  geom_bar(stat = "identity", position = "stack") +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))



qp_data %>%
  ggplot(
    aes(x = Balearic_Islands_language_residents_learn, fill = gender)) +
  geom_bar(position = "dodge", stat = "count")

qp_data %>%
  group_by(Balearic_Islands_language_residents_learn, gender) %>%
  summarise(count = n()) %>%
  ggplot(aes(x = Balearic_Islands_language_residents_learn, y = count, fill = gender)) +
  geom_bar(stat = "identity", position = "stack") +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))


```


```{r}

qp_data |> 
  select(catalan_proficiency_understand:spanish_proficiency_write) |>
  pivot_longer(
    col = catalan_proficiency_understand:spanish_proficiency_write, 
    names_to = "Skills", 
    values_to = "avg"
  ) |>
  separate(Skills, into = c("language", "Skills"), sep = 7) |>
  mutate(Skills = stringr::str_remove(Skills, "\\_proficiency\\_")) |>
  group_by(language, Skills) |>
  count(avg) |>
  mutate(prop = n / 99) |>
  ggplot() +
  aes(x = Skills, y = prop, fill = language) +
  geom_bar(stat = "identity", position = "dodge")


qp_data |> 
  select(catalan_proficiency_understand:spanish_proficiency_write) |>
  pivot_longer(
    col = catalan_proficiency_understand:spanish_proficiency_write, 
    names_to = "Skills", 
    values_to = "avg"
  ) |>
  separate(Skills, into = c("language", "Skills"), sep = 7) |>
  mutate(Skills = stringr::str_remove(Skills, "\\_proficiency\\_")) |>
  mutate(language = case_when(
    language == "catalan" ~ "Catalan",
    language == "spanish" ~ "Spanish",
    TRUE ~ "Prop"
  )) |>
  group_by(language, Skills) |>
  count(avg) |>
  mutate(prop = n / 99) |>
  ggplot() +
  aes(x = Skills, y = prop, fill = language) +
  geom_bar(stat = "identity", position = "dodge")


```

